package main

import (
	"context"
	"errors"
	"log"
	"net/http"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger/v2"

	"github.com/kubik/bank-system/internal/config"
	"github.com/kubik/bank-system/internal/db"
	"github.com/kubik/bank-system/internal/handler"
	"github.com/kubik/bank-system/internal/keycloak"
	"github.com/kubik/bank-system/internal/orca"
	"github.com/kubik/bank-system/internal/processing"
	"github.com/kubik/bank-system/internal/scheduler"

	// Registers the parsed swagger spec with swaggo's global template
	// registry (see its own init()) — only imported for that side effect,
	// only referenced (via httpSwagger.WrapHandler below) when
	// EnableSwaggerDocs is set. Generated by `make swagger` — never hand-edit
	// internal/swaggerdocs/* directly.
	_ "github.com/kubik/bank-system/internal/swaggerdocs"
	"github.com/kubik/bank-system/internal/syncjob"
)

// @title Bank System API
// @version 1.0
// @description Private bank API — syncs Fio Bank transaction data into Postgres, matches member payments to their bank transactions, and detects missed dues. Dev-only documentation (see config.EnableSwaggerDocs): every route below requires a Keycloak bearer token unless noted otherwise.
// @BasePath /api
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Keycloak-issued bearer token for bank-system's Keycloak client, sent as `Authorization: Bearer <token>`. Which role(s) a given route requires is noted on that route below — see internal/keycloak.Role for the full list.
func main() {
	appConfig, err := config.Load()
	if err != nil {
		log.Fatal(err)
	}

	requestContext, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	pool, err := pgxpool.New(requestContext, appConfig.DatabaseURL)
	if err != nil {
		log.Fatalf("db pool: %v", err)
	}
	defer pool.Close()

	pingContext, cancel := context.WithTimeout(requestContext, 5*time.Second)
	defer cancel()
	if err := pool.Ping(pingContext); err != nil {
		log.Fatalf("db ping: %v", err)
	}

	if fioCount, orcaCount, err := syncjob.FailStaleRuns(requestContext, pool); err != nil {
		log.Printf("failing stale sync runs: %v", err)
	} else if fioCount > 0 || orcaCount > 0 {
		log.Printf("failed stale sync runs from a previous process: sync_fio_runs=%d sync_orca_runs=%d", fioCount, orcaCount)
	}

	// One daily job, run in order: Orca (members) before Fio (transactions) —
	// transaction processing (member payment matching, not built yet) needs
	// both done first, so it can't run as two independently-scheduled jobs.
	//
	// schedulerDone is waited on below (deferred after pool.Close(), so it
	// runs first on the way out) so shutdown doesn't
	// close the pool out from under a sync/processing run that's still
	// in-flight when SIGINT/SIGTERM arrives: RunImmediatellyAndThenDaily only
	// stops waiting for the *next* scheduled run on cancellation, it doesn't
	// abort a run already in progress.
	var schedulerDone sync.WaitGroup
	schedulerDone.Add(1)
	defer schedulerDone.Wait()

	orcaClient := orca.NewClient(appConfig.OrcaAPIURL, appConfig.OrcaSyncToken, appConfig.Debug)
	go func() {
		defer schedulerDone.Done()
		scheduler.RunImmediatellyAndThenDaily(requestContext, 3, 0, func(runContext context.Context) {

			// We don't care about Orca sync result. We wil always try to match new transactions, if Fio returns anything new
			if result, err := syncjob.RunOrcaSync(runContext, pool, orcaClient); err != nil {
				log.Printf("orca sync: %v", err)
			} else {
				log.Printf("orca sync: members_fetched=%d members_upserted=%d", result.MembersFetched, result.MembersUpserted)
			}

			fioOK := true
			if appConfig.Debug {
				log.Print("fio sync: skipped (DEBUG=true) — use `make seed` for local fixture data")
			} else if results, err := syncjob.RunFioSync(runContext, pool, appConfig.FioAPIURL, appConfig.BankTokenEncryptionKey, appConfig.Debug); err != nil {
				fioOK = false
				log.Printf("fio sync: %v", err)
			} else {
				for _, r := range results {
					log.Printf("fio sync: bank_account_id=%d fetched=%d inserted=%d", r.BankAccountID, r.TransactionsFetched, r.TransactionsInserted)
				}
			}

			if !fioOK {
				log.Print("transaction processing: skipped, a Fio sync step failed this run")
				return
			}

			result, err := processing.Run(runContext, pool)
			if err != nil {
				log.Printf("transaction processing: %v", err)
				return
			}
			log.Printf("transaction processing: processed=%d failed=%d", result.TransactionsProcessed, result.TransactionsFailed)
		})
	}()

	keycloakProvider, err := keycloak.NewProvider(appConfig.KeycloakHost, appConfig.KeycloakRealm, appConfig.KeycloakClientID)
	if err != nil {
		log.Fatalf("keycloak: %v", err)
	}

	// All application routes live under /api so a reverse proxy can serve the
	// frontend at / and forward only /api/ here (see docs deploy notes). Handler
	// patterns below stay unprefixed; StripPrefix trims /api before matching.
	api := http.NewServeMux()

	api.HandleFunc("GET /account", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.ListBankAccounts(db.New(pool))))
	api.HandleFunc("POST /account", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.CreateBankAccount(db.New(pool), appConfig.BankTokenEncryptionKey)))
	api.HandleFunc("PATCH /account/{id}", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.UpdateBankAccount(db.New(pool), appConfig.BankTokenEncryptionKey)))
	api.HandleFunc("DELETE /account/{id}", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.DeleteBankAccount(db.New(pool))))
	api.HandleFunc("POST /account/{id}/sync", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.TriggerFioSync(pool, appConfig.FioAPIURL, appConfig.BankTokenEncryptionKey, appConfig.Debug)))
	api.HandleFunc("POST /account/{id}/backfill", handler.RequireRole(keycloakProvider, keycloak.RoleManageBankAccounts, handler.BackfillAccount(pool, appConfig.FioAPIURL, appConfig.BankTokenEncryptionKey, appConfig.Debug)))
	api.HandleFunc("POST /processing/run", handler.RequireAnyRole(keycloakProvider, []keycloak.Role{keycloak.RoleManageBankAccounts, keycloak.RoleManageTransactions}, handler.RunProcessing(pool, keycloakProvider)))

	api.HandleFunc("GET /event-logs", handler.RequireRole(keycloakProvider, keycloak.RoleViewEventLogs, handler.ListEventLogs(db.New(pool))))

	api.HandleFunc("GET /transactions", handler.RequireRole(keycloakProvider, keycloak.RoleListTransactions, handler.ListTransactions(db.New(pool))))
	api.HandleFunc("GET /transactions/summary", handler.RequireRole(keycloakProvider, keycloak.RoleViewBudget, handler.CategorySummary(db.New(pool))))
	api.HandleFunc("GET /transactions/{id}", handler.RequireRole(keycloakProvider, keycloak.RoleListTransactions, handler.GetTransaction(db.New(pool))))
	api.HandleFunc("PUT /transactions/{id}/assignment", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.AssignTransaction(pool)))
	api.HandleFunc("DELETE /transactions/{id}/assignment", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.UnassignTransaction(pool)))

	api.HandleFunc("GET /categories", handler.RequireRole(keycloakProvider, keycloak.RoleListTransactions, handler.ListCategories(db.New(pool))))
	api.HandleFunc("POST /categories", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.CreateCategory(db.New(pool))))
	api.HandleFunc("DELETE /categories/{name}", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.DeleteCategory(db.New(pool))))
	api.HandleFunc("GET /payments/{member_number}/history", handler.RequireAnyRole(keycloakProvider, []keycloak.Role{keycloak.RolePaymentHistory, keycloak.RoleViewWorkplacePaymentHistory}, handler.PaymentHistory(keycloakProvider, db.New(pool))))
	api.HandleFunc("GET /payments/me/history", handler.RequireAuth(keycloakProvider, handler.MyPaymentHistory(db.New(pool))))
	api.HandleFunc("GET /payments/{year}/{month}/missing", handler.RequireRole(keycloakProvider, keycloak.RolePaymentHistory, handler.MissingPayments(db.New(pool))))
	api.HandleFunc("GET /payments/{year}/missing", handler.RequireRole(keycloakProvider, keycloak.RolePaymentHistory, handler.MissingPaymentsInYear(db.New(pool))))
	api.HandleFunc("GET /payments/workplace/{year}/{month}/missing", handler.RequireRole(keycloakProvider, keycloak.RoleViewWorkplacePaymentHistory, handler.WorkplaceMissingPayments(keycloakProvider, db.New(pool))))
	api.HandleFunc("GET /payments/workplace/{year}/missing", handler.RequireRole(keycloakProvider, keycloak.RoleViewWorkplacePaymentHistory, handler.WorkplaceMissingPaymentsInYear(keycloakProvider, db.New(pool))))
	api.HandleFunc("GET /payments/{year}/{month}/commented", handler.RequireRole(keycloakProvider, keycloak.RolePaymentHistory, handler.CommentedTransactions(db.New(pool))))
	api.HandleFunc("GET /payments/{year}/commented", handler.RequireRole(keycloakProvider, keycloak.RolePaymentHistory, handler.CommentedTransactionsInYear(db.New(pool))))
	api.HandleFunc("GET /payments/workplace/{year}/{month}/commented", handler.RequireRole(keycloakProvider, keycloak.RoleViewWorkplacePaymentHistory, handler.WorkplaceCommentedTransactions(keycloakProvider, db.New(pool))))
	api.HandleFunc("GET /payments/workplace/{year}/commented", handler.RequireRole(keycloakProvider, keycloak.RoleViewWorkplacePaymentHistory, handler.WorkplaceCommentedTransactionsInYear(keycloakProvider, db.New(pool))))
	api.HandleFunc("GET /payments/waivers", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.ListWaivers(db.New(pool))))
	api.HandleFunc("POST /payments/{member_number}/waive", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.WaivePayment(db.New(pool))))
	api.HandleFunc("DELETE /payments/{member_number}/waive/{year}/{month}", handler.RequireRole(keycloakProvider, keycloak.RoleManageTransactions, handler.UnwaivePayment(db.New(pool))))

	// Dev-only Swagger UI, off by default (see config.EnableSwaggerDocs).
	// Mounted under /api like everything else, at /api/docs/index.html.
	if appConfig.EnableSwaggerDocs {
		api.HandleFunc("GET /docs/", httpSwagger.WrapHandler)
		log.Print("swagger docs enabled at /api/docs/index.html")
	}

	mux := http.NewServeMux()
	mux.Handle("/api/", http.StripPrefix("/api", api))

	// rs/cors treats an empty AllowedOrigins as "allow every origin" (its
	// zero-value default), the opposite of what we want when
	// CorsAllowedOrigins is unset — so only wrap with it when there's an
	// actual allow-list. Cross-origin callers (e.g. Orca's own frontend)
	// need this; this API's own frontend is always same-origin (nginx/Vite
	// both proxy /api/ alongside it) and never needs CORS headers at all.
	var apiHandler http.Handler = mux
	if len(appConfig.CorsAllowedOrigins) > 0 {
		apiHandler = cors.New(cors.Options{
			AllowedOrigins: appConfig.CorsAllowedOrigins,
			AllowedMethods: []string{http.MethodGet, http.MethodPost, http.MethodPut, http.MethodPatch, http.MethodDelete},
			AllowedHeaders: []string{"Authorization", "Content-Type"},
			MaxAge:         600,
		}).Handler(mux)
	}

	server := &http.Server{
		Addr:    appConfig.Addr,
		Handler: handler.Recover(handler.MaxBodySize(handler.MaxRequestBodySize, apiHandler)),
		// Slowloris mitigation: without these, a client that trickles bytes (or
		// never sends any) can hold a connection — and the goroutine serving it
		// — open indefinitely. ReadHeaderTimeout/ReadTimeout bound how long a
		// slow/stalled request can occupy a connection; IdleTimeout bounds how
		// long a keep-alive connection sits open between requests.
		//
		// WriteTimeout is deliberately generous rather than tight: it's a
		// per-connection deadline covering the whole request-to-response
		// cycle, and TriggerFioSync/BackfillAccount ([internal/handler/account.go])
		// call the live Fio API and then run transaction processing
		// synchronously before responding — a tight timeout here would risk
		// the admin UI seeing a connection reset on a slow-but-legitimate sync,
		// even though the sync itself completed server-side.
		ReadHeaderTimeout: 5 * time.Second,
		ReadTimeout:       15 * time.Second,
		WriteTimeout:      2 * time.Minute,
		IdleTimeout:       120 * time.Second,
	}

	go func() {
		<-requestContext.Done()
		shutdownContext, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := server.Shutdown(shutdownContext); err != nil {
			log.Printf("shutdown: %v", err)
		}
	}()

	log.Printf("listening on %s", appConfig.Addr)
	if err := server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
}
