// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	ID           int32     `json:"id"`
	FioAccountID string    `json:"fio_account_id"`
	Iban         *string   `json:"iban"`
	Currency     string    `json:"currency"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type Member struct {
	MemberNumber int32       `json:"member_number"`
	FeeStartDate pgtype.Date `json:"fee_start_date"`
	Active       bool        `json:"active"`
	CreatedAt    time.Time   `json:"created_at"`
	Sub          pgtype.UUID `json:"sub"`
	FeeStopDate  pgtype.Date `json:"fee_stop_date"`
}

type MemberPaymentIdentifier struct {
	ID             int32       `json:"id"`
	MemberNumber   int32       `json:"member_number"`
	VariableSymbol string      `json:"variable_symbol"`
	ValidFrom      time.Time   `json:"valid_from"`
	ValidTo        pgtype.Date `json:"valid_to"`
}

type PaymentCoverage struct {
	ID                     int64 `json:"id"`
	ProcessedTransactionID int64 `json:"processed_transaction_id"`
	MemberNumber           int32 `json:"member_number"`
	CoversYear             int32 `json:"covers_year"`
	CoversMonth            int16 `json:"covers_month"`
}

type ProcessedTransaction struct {
	ID               int64     `json:"id"`
	RawTransactionID int64     `json:"raw_transaction_id"`
	MemberNumber     *int32    `json:"member_number"`
	Category         string    `json:"category"`
	Direction        string    `json:"direction"`
	MatchedBy        *string   `json:"matched_by"`
	IsPublicVisible  bool      `json:"is_public_visible"`
	ProcessedAt      time.Time `json:"processed_at"`
}

type RawTransaction struct {
	ID                   int64     `json:"id"`
	BankAccountID        int32     `json:"bank_account_id"`
	FioTransactionID     int64     `json:"fio_transaction_id"`
	TransactionDate      time.Time `json:"transaction_date"`
	Amount               string    `json:"amount"`
	Currency             string    `json:"currency"`
	CounterAccountNumber *string   `json:"counter_account_number"`
	CounterAccountName   *string   `json:"counter_account_name"`
	CounterBankCode      *string   `json:"counter_bank_code"`
	CounterBankName      *string   `json:"counter_bank_name"`
	Bic                  *string   `json:"bic"`
	VariableSymbol       *string   `json:"variable_symbol"`
	SpecificSymbol       *string   `json:"specific_symbol"`
	ConstantSymbol       *string   `json:"constant_symbol"`
	UserIdentification   *string   `json:"user_identification"`
	MessageForRecipient  *string   `json:"message_for_recipient"`
	TransactionType      *string   `json:"transaction_type"`
	Executor             *string   `json:"executor"`
	Specification        *string   `json:"specification"`
	Comment              *string   `json:"comment"`
	InstructionID        *string   `json:"instruction_id"`
	RawPayload           []byte    `json:"raw_payload"`
	SyncedAt             time.Time `json:"synced_at"`
}

type SyncFioRun struct {
	ID                   int64              `json:"id"`
	BankAccountID        int32              `json:"bank_account_id"`
	StartedAt            time.Time          `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	Status               string             `json:"status"`
	TransactionsFetched  *int32             `json:"transactions_fetched"`
	TransactionsInserted *int32             `json:"transactions_inserted"`
	ErrorMessage         *string            `json:"error_message"`
}

type SyncOrcaRun struct {
	ID              int64              `json:"id"`
	StartedAt       time.Time          `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	Status          string             `json:"status"`
	MembersFetched  *int32             `json:"members_fetched"`
	MembersUpserted *int32             `json:"members_upserted"`
	ErrorMessage    *string            `json:"error_message"`
}
