// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error)
	CreatePaymentCoverage(ctx context.Context, arg CreatePaymentCoverageParams) error
	CreateProcessedTransaction(ctx context.Context, arg CreateProcessedTransactionParams) (ProcessedTransaction, error)
	CreateSyncFioRun(ctx context.Context, bankAccountID int32) (SyncFioRun, error)
	CreateSyncOrcaRun(ctx context.Context) (SyncOrcaRun, error)
	// Seeds the auto-generated "default" payment identifier for a member: variable
	// symbol == member_number, valid from their fee_start_date. Runs on every Orca
	// sync. DO NOTHING on conflict so a re-run is a no-op. Skipped by the caller when
	// fee_start_date is null (member not yet liable, and valid_from is NOT NULL).
	EnsureDefaultPaymentIdentifier(ctx context.Context, arg EnsureDefaultPaymentIdentifierParams) error
	FindMemberByVariableSymbol(ctx context.Context, arg FindMemberByVariableSymbolParams) (int32, error)
	FinishSyncFioRun(ctx context.Context, arg FinishSyncFioRunParams) error
	FinishSyncOrcaRun(ctx context.Context, arg FinishSyncOrcaRunParams) error
	GetMaxFioTransactionID(ctx context.Context, bankAccountID int32) (int64, error)
	GetMemberNumberBySub(ctx context.Context, sub pgtype.UUID) (int32, error)
	GetPaymentHistory(ctx context.Context, memberNumber int32) ([]GetPaymentHistoryRow, error)
	InsertRawTransaction(ctx context.Context, arg InsertRawTransactionParams) (int64, error)
	ListBankAccounts(ctx context.Context) ([]BankAccount, error)
	ListMembers(ctx context.Context) ([]Member, error)
	// Members who were liable for the membership fee in the given year/month but
	// have no payment_coverage row for it. "Liable" = fee_start_date is set (the
	// member_arrears view enforces this) and the target month falls within
	// [fee_start_date, COALESCE(fee_stop_date, CURRENT_DATE)] at month granularity.
	//
	// total_missed_months comes from the member_arrears view: a total-arrears figure
	// independent of the queried month (every unpaid month across the member's full
	// liability window). Always >= 1 here, since the queried month is one of them.
	// Rows are ordered by it descending ("top offenders first"), member_number
	// breaking ties. See docs/logic-design.md "Missed Payment Detection".
	ListMembersMissingPayment(ctx context.Context, arg ListMembersMissingPaymentParams) ([]MemberArrear, error)
	// Members who missed at least one liable month during the given calendar year —
	// the whole-year counterpart of ListMembersMissingPayment. Same
	// {member_number, total_missed_months} shape and ordering; total_missed_months
	// is still the full-liability-window arrears count (member_arrears view), not
	// scoped to the year. See docs/logic-design.md "Missed Payment Detection".
	ListMembersMissingPaymentInYear(ctx context.Context, year int32) ([]MemberArrear, error)
	ListUnprocessedTransactions(ctx context.Context) ([]RawTransaction, error)
	// Mirrors members.fee_stop_date onto the default payment identifier's valid_to
	// (variable_symbol == member_number): fee liability ended -> row closed with that
	// date, fee_stop_date cleared in Orca -> row reopened (valid_to = NULL). The sync
	// owns this row's window authoritatively (valid_from = fee_start_date, valid_to =
	// fee_stop_date). To point a member at a different variable symbol, add a *new*
	// member_payment_identifiers row (different variable_symbol, its own valid_from) —
	// that row has variable_symbol != member_number so this UPDATE never touches it.
	// The IS DISTINCT FROM guard makes a steady-state run write nothing.
	SyncDefaultPaymentIdentifierValidTo(ctx context.Context, arg SyncDefaultPaymentIdentifierValidToParams) error
	UpsertMember(ctx context.Context, arg UpsertMemberParams) error
}

var _ Querier = (*Queries)(nil)
