// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTransactionToMember = `-- name: AssignTransactionToMember :one
UPDATE processed_transactions
SET member_number = $1,
    category = $2,
    matched_by = $3,
    admin_comment = $4
WHERE id = $5
RETURNING id
`

type AssignTransactionToMemberParams struct {
	MemberNumber *int32  `json:"member_number"`
	Category     string  `json:"category"`
	MatchedBy    *string `json:"matched_by"`
	AdminComment *string `json:"admin_comment"`
	ID           int64   `json:"id"`
}

// Manual categorization, with or without a member match — member_number and
// matched_by are both nullable so a category-only edit (no member) just
// passes both as NULL. Coverage rows are managed separately by the caller in
// the same DB transaction. admin_comment is also a full overwrite, same as
// member_number — the caller (handler.AssignTransaction) always resends the
// intended value, NULL clears it.
func (q *Queries) AssignTransactionToMember(ctx context.Context, arg AssignTransactionToMemberParams) (int64, error) {
	row := q.db.QueryRow(ctx, assignTransactionToMember,
		arg.MemberNumber,
		arg.Category,
		arg.MatchedBy,
		arg.AdminComment,
		arg.ID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS (SELECT 1 FROM transaction_categories WHERE name = $1) AS exists
`

func (q *Queries) CategoryExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (fio_account_id, iban, currency, display_name, fio_token_encrypted)
VALUES (
    $1,
    $2,
    $3,
    $4,
    pgp_sym_encrypt($5::text, $6::text)
)
RETURNING id, fio_account_id, iban, currency, display_name, created_at
`

type CreateBankAccountParams struct {
	FioAccountID  string  `json:"fio_account_id"`
	Iban          *string `json:"iban"`
	Currency      string  `json:"currency"`
	DisplayName   string  `json:"display_name"`
	FioToken      string  `json:"fio_token"`
	EncryptionKey string  `json:"encryption_key"`
}

type CreateBankAccountRow struct {
	ID           int32     `json:"id"`
	FioAccountID string    `json:"fio_account_id"`
	Iban         *string   `json:"iban"`
	Currency     string    `json:"currency"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
}

// fio_token is encrypted at rest via pgcrypto (pgp_sym_encrypt) using
// encryption_key (BANK_TOKEN_ENCRYPTION_KEY env var) — never stored in the DB
// itself. RETURNING list explicitly excludes fio_token_encrypted so the
// ciphertext (and a fortiori the token) is never echoed back to the caller.
func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (CreateBankAccountRow, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.FioAccountID,
		arg.Iban,
		arg.Currency,
		arg.DisplayName,
		arg.FioToken,
		arg.EncryptionKey,
	)
	var i CreateBankAccountRow
	err := row.Scan(
		&i.ID,
		&i.FioAccountID,
		&i.Iban,
		&i.Currency,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO transaction_categories (name, is_mandatory) VALUES ($1, false)
RETURNING name, is_mandatory, created_at
`

// is_mandatory is never set true here — only the four seeded in
// migrations/20260910000001_add_transaction_categories.sql are mandatory.
func (q *Queries) CreateCategory(ctx context.Context, name string) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i TransactionCategory
	err := row.Scan(&i.Name, &i.IsMandatory, &i.CreatedAt)
	return i, err
}

const createPaymentCoverage = `-- name: CreatePaymentCoverage :execrows
INSERT INTO payment_coverage (processed_transaction_id, member_number, covers_year, covers_month)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_number, covers_year, covers_month) DO NOTHING
`

type CreatePaymentCoverageParams struct {
	ProcessedTransactionID int64 `json:"processed_transaction_id"`
	MemberNumber           int32 `json:"member_number"`
	CoversYear             int32 `json:"covers_year"`
	CoversMonth            int16 `json:"covers_month"`
}

// ON CONFLICT DO NOTHING + :execrows (same pattern as InsertCoverageRow) so
// the caller can tell when a second payment lands on an already-covered
// month — see internal/processing/processing.go's log line, since this path
// (unlike the manual assignment endpoint) has no HTTP response to surface it
// through.
func (q *Queries) CreatePaymentCoverage(ctx context.Context, arg CreatePaymentCoverageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPaymentCoverage,
		arg.ProcessedTransactionID,
		arg.MemberNumber,
		arg.CoversYear,
		arg.CoversMonth,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPaymentWaiver = `-- name: CreatePaymentWaiver :execrows
INSERT INTO payment_waivers (member_number, covers_year, covers_month, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_number, covers_year, covers_month) DO NOTHING
`

type CreatePaymentWaiverParams struct {
	MemberNumber int32  `json:"member_number"`
	CoversYear   int32  `json:"covers_year"`
	CoversMonth  int16  `json:"covers_month"`
	Reason       string `json:"reason"`
}

// ON CONFLICT DO NOTHING + :execrows, same idempotent-insert pattern as
// CreatePaymentCoverage/InsertCoverageRow — calling this twice for the same
// month is a no-op (0 rows affected), not an error, since the caller's
// intent ("this month is written off") is already satisfied.
func (q *Queries) CreatePaymentWaiver(ctx context.Context, arg CreatePaymentWaiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPaymentWaiver,
		arg.MemberNumber,
		arg.CoversYear,
		arg.CoversMonth,
		arg.Reason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createProcessedTransaction = `-- name: CreateProcessedTransaction :one
INSERT INTO processed_transactions (raw_transaction_id, member_number, category, direction, matched_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, raw_transaction_id, member_number, category, direction, matched_by, is_public_visible, processed_at, admin_comment
`

type CreateProcessedTransactionParams struct {
	RawTransactionID int64   `json:"raw_transaction_id"`
	MemberNumber     *int32  `json:"member_number"`
	Category         string  `json:"category"`
	Direction        string  `json:"direction"`
	MatchedBy        *string `json:"matched_by"`
}

func (q *Queries) CreateProcessedTransaction(ctx context.Context, arg CreateProcessedTransactionParams) (ProcessedTransaction, error) {
	row := q.db.QueryRow(ctx, createProcessedTransaction,
		arg.RawTransactionID,
		arg.MemberNumber,
		arg.Category,
		arg.Direction,
		arg.MatchedBy,
	)
	var i ProcessedTransaction
	err := row.Scan(
		&i.ID,
		&i.RawTransactionID,
		&i.MemberNumber,
		&i.Category,
		&i.Direction,
		&i.MatchedBy,
		&i.IsPublicVisible,
		&i.ProcessedAt,
		&i.AdminComment,
	)
	return i, err
}

const createSyncFioRun = `-- name: CreateSyncFioRun :one
INSERT INTO sync_fio_runs (bank_account_id, status)
VALUES ($1, 'running')
RETURNING id, bank_account_id, started_at, finished_at, status, transactions_fetched, transactions_inserted, error_message
`

func (q *Queries) CreateSyncFioRun(ctx context.Context, bankAccountID int32) (SyncFioRun, error) {
	row := q.db.QueryRow(ctx, createSyncFioRun, bankAccountID)
	var i SyncFioRun
	err := row.Scan(
		&i.ID,
		&i.BankAccountID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TransactionsFetched,
		&i.TransactionsInserted,
		&i.ErrorMessage,
	)
	return i, err
}

const createSyncOrcaRun = `-- name: CreateSyncOrcaRun :one
INSERT INTO sync_orca_runs (status)
VALUES ('running')
RETURNING id, started_at, finished_at, status, members_fetched, members_upserted, error_message
`

func (q *Queries) CreateSyncOrcaRun(ctx context.Context) (SyncOrcaRun, error) {
	row := q.db.QueryRow(ctx, createSyncOrcaRun)
	var i SyncOrcaRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.MembersFetched,
		&i.MembersUpserted,
		&i.ErrorMessage,
	)
	return i, err
}

const deleteBankAccount = `-- name: DeleteBankAccount :execrows
UPDATE bank_accounts SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete: raw_transactions/sync_fio_runs reference bank_accounts.id with
// no ON DELETE clause (see initial_schema.sql), so a hard delete would fail
// once an account has synced history — and the row also needs to stick around
// for admins to see it used to exist (see ListBankAccounts). deleted_at IS
// NULL in the WHERE guards against re-timestamping an already-deleted row;
// :execrows lets handler.DeleteBankAccount tell "already gone" (0 rows) from
// "deleted just now" (1 row) and return 404 vs 204 accordingly.
func (q *Queries) DeleteBankAccount(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBankAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM transaction_categories WHERE name = $1 AND is_mandatory = false
`

// The is_mandatory=false guard means a mandatory category and a missing one
// both come back as 0 rows affected — the caller (handler.DeleteCategory)
// checks GetCategory first to tell those two cases apart. A category still
// referenced by processed_transactions.category fails this with a foreign
// key violation instead (see processed_transactions_category_fkey).
func (q *Queries) DeleteCategory(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCoverageForTransaction = `-- name: DeleteCoverageForTransaction :exec
DELETE FROM payment_coverage WHERE processed_transaction_id = $1
`

func (q *Queries) DeleteCoverageForTransaction(ctx context.Context, processedTransactionID int64) error {
	_, err := q.db.Exec(ctx, deleteCoverageForTransaction, processedTransactionID)
	return err
}

const deletePaymentWaiver = `-- name: DeletePaymentWaiver :execrows
DELETE FROM payment_waivers
WHERE member_number = $1
  AND covers_year = $2
  AND covers_month = $3
`

type DeletePaymentWaiverParams struct {
	MemberNumber int32 `json:"member_number"`
	CoversYear   int32 `json:"covers_year"`
	CoversMonth  int16 `json:"covers_month"`
}

// Undoes a waiver (the admin changed their mind, or waived the wrong
// month) — the month reappears in missing-payment lists on the next read,
// same as any other computed-on-read state here.
func (q *Queries) DeletePaymentWaiver(ctx context.Context, arg DeletePaymentWaiverParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePaymentWaiver, arg.MemberNumber, arg.CoversYear, arg.CoversMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureDefaultPaymentIdentifier = `-- name: EnsureDefaultPaymentIdentifier :exec
INSERT INTO member_payment_identifiers (member_number, variable_symbol, valid_from)
VALUES ($1, $2, $3)
ON CONFLICT (variable_symbol, valid_from) DO NOTHING
`

type EnsureDefaultPaymentIdentifierParams struct {
	MemberNumber   int32     `json:"member_number"`
	VariableSymbol string    `json:"variable_symbol"`
	ValidFrom      time.Time `json:"valid_from"`
}

// Seeds the auto-generated "default" payment identifier for a member: variable
// symbol == member_number, valid from their fee_start_date. Runs on every Orca
// sync. DO NOTHING on conflict so a re-run is a no-op. Skipped by the caller when
// fee_start_date is null (member not yet liable, and valid_from is NOT NULL).
func (q *Queries) EnsureDefaultPaymentIdentifier(ctx context.Context, arg EnsureDefaultPaymentIdentifierParams) error {
	_, err := q.db.Exec(ctx, ensureDefaultPaymentIdentifier, arg.MemberNumber, arg.VariableSymbol, arg.ValidFrom)
	return err
}

const failStaleSyncFioRuns = `-- name: FailStaleSyncFioRuns :execrows
UPDATE sync_fio_runs
SET finished_at = now(),
    status = 'failed',
    error_message = 'interrupted: server restarted mid-run'
WHERE status = 'running'
`

// Run once at server startup, before the scheduler starts: any row still
// 'running' predates this process (a single instance drives all syncs, so a
// 'running' row at boot means the prior process died — crash, panic, kill —
// between CreateSyncFioRun and FinishSyncFioRun and never got to close it).
func (q *Queries) FailStaleSyncFioRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleSyncFioRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleSyncOrcaRuns = `-- name: FailStaleSyncOrcaRuns :execrows
UPDATE sync_orca_runs
SET finished_at = now(),
    status = 'failed',
    error_message = 'interrupted: server restarted mid-run'
WHERE status = 'running'
`

// See FailStaleSyncFioRuns — same reasoning, run at startup.
func (q *Queries) FailStaleSyncOrcaRuns(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleSyncOrcaRuns)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findMemberByVariableSymbol = `-- name: FindMemberByVariableSymbol :one
SELECT member_number FROM member_payment_identifiers
WHERE variable_symbol = $1
    AND valid_from <= $2
    AND (valid_to IS NULL OR valid_to >= $2)
ORDER BY valid_from DESC
LIMIT 1
`

type FindMemberByVariableSymbolParams struct {
	VariableSymbol  string    `json:"variable_symbol"`
	TransactionDate time.Time `json:"transaction_date"`
}

func (q *Queries) FindMemberByVariableSymbol(ctx context.Context, arg FindMemberByVariableSymbolParams) (int32, error) {
	row := q.db.QueryRow(ctx, findMemberByVariableSymbol, arg.VariableSymbol, arg.TransactionDate)
	var member_number int32
	err := row.Scan(&member_number)
	return member_number, err
}

const finishSyncFioRun = `-- name: FinishSyncFioRun :exec
UPDATE sync_fio_runs
SET finished_at = now(),
    status = $1,
    transactions_fetched = $2,
    transactions_inserted = $3,
    error_message = $4
WHERE id = $5
`

type FinishSyncFioRunParams struct {
	Status               string  `json:"status"`
	TransactionsFetched  *int32  `json:"transactions_fetched"`
	TransactionsInserted *int32  `json:"transactions_inserted"`
	ErrorMessage         *string `json:"error_message"`
	ID                   int64   `json:"id"`
}

func (q *Queries) FinishSyncFioRun(ctx context.Context, arg FinishSyncFioRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncFioRun,
		arg.Status,
		arg.TransactionsFetched,
		arg.TransactionsInserted,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const finishSyncOrcaRun = `-- name: FinishSyncOrcaRun :exec
UPDATE sync_orca_runs
SET finished_at = now(),
    status = $1,
    members_fetched = $2,
    members_upserted = $3,
    error_message = $4
WHERE id = $5
`

type FinishSyncOrcaRunParams struct {
	Status          string  `json:"status"`
	MembersFetched  *int32  `json:"members_fetched"`
	MembersUpserted *int32  `json:"members_upserted"`
	ErrorMessage    *string `json:"error_message"`
	ID              int64   `json:"id"`
}

func (q *Queries) FinishSyncOrcaRun(ctx context.Context, arg FinishSyncOrcaRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncOrcaRun,
		arg.Status,
		arg.MembersFetched,
		arg.MembersUpserted,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const getBankAccountWithToken = `-- name: GetBankAccountWithToken :one
SELECT id, fio_account_id, iban, currency, display_name, created_at,
       pgp_sym_decrypt(fio_token_encrypted, $1::text) AS fio_token,
       (deleted_at IS NULL)::boolean AS is_active
FROM bank_accounts WHERE id = $2
`

type GetBankAccountWithTokenParams struct {
	EncryptionKey string `json:"encryption_key"`
	ID            int32  `json:"id"`
}

type GetBankAccountWithTokenRow struct {
	ID           int32     `json:"id"`
	FioAccountID string    `json:"fio_account_id"`
	Iban         *string   `json:"iban"`
	Currency     string    `json:"currency"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	FioToken     string    `json:"fio_token"`
	IsActive     bool      `json:"is_active"`
}

// Internal use only (the manual "sync now" trigger — see
// syncjob.SyncOneAccount) — single-row counterpart of
// ListBankAccountsWithToken, same never-expose-over-HTTP caveat.
func (q *Queries) GetBankAccountWithToken(ctx context.Context, arg GetBankAccountWithTokenParams) (GetBankAccountWithTokenRow, error) {
	row := q.db.QueryRow(ctx, getBankAccountWithToken, arg.EncryptionKey, arg.ID)
	var i GetBankAccountWithTokenRow
	err := row.Scan(
		&i.ID,
		&i.FioAccountID,
		&i.Iban,
		&i.Currency,
		&i.DisplayName,
		&i.CreatedAt,
		&i.FioToken,
		&i.IsActive,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT name, is_mandatory, created_at FROM transaction_categories WHERE name = $1
`

func (q *Queries) GetCategory(ctx context.Context, name string) (TransactionCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, name)
	var i TransactionCategory
	err := row.Scan(&i.Name, &i.IsMandatory, &i.CreatedAt)
	return i, err
}

const getMaxFioTransactionID = `-- name: GetMaxFioTransactionID :one
SELECT COALESCE(MAX(fio_transaction_id), 0)::bigint AS max_id
FROM raw_transactions
WHERE bank_account_id = $1
`

func (q *Queries) GetMaxFioTransactionID(ctx context.Context, bankAccountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxFioTransactionID, bankAccountID)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const getMemberNumberBySub = `-- name: GetMemberNumberBySub :one
SELECT member_number FROM members WHERE sub = $1
`

func (q *Queries) GetMemberNumberBySub(ctx context.Context, sub pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMemberNumberBySub, sub)
	var member_number int32
	err := row.Scan(&member_number)
	return member_number, err
}

const getMemberWorkplaceSub = `-- name: GetMemberWorkplaceSub :one
SELECT workplace_executive_committee_sub FROM members WHERE member_number = $1
`

// Backs the workplace-rep access path on GET /payments/{member_number}/history:
// a caller without the
// admin payment-history role can still see this member if the returned value
// is non-null and matches one of the caller's own Keycloak groups.
func (q *Queries) GetMemberWorkplaceSub(ctx context.Context, memberNumber int32) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMemberWorkplaceSub, memberNumber)
	var workplace_executive_committee_sub pgtype.UUID
	err := row.Scan(&workplace_executive_committee_sub)
	return workplace_executive_committee_sub, err
}

const getPaymentHistory = `-- name: GetPaymentHistory :many
SELECT pc.covers_year, pc.covers_month,
       rt.transaction_date, rt.amount, rt.currency,
       pc.processed_transaction_id
FROM payment_coverage pc
JOIN processed_transactions pt ON pt.id = pc.processed_transaction_id
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pc.member_number = $1
ORDER BY pc.covers_year DESC, pc.covers_month DESC
`

type GetPaymentHistoryRow struct {
	CoversYear             int32     `json:"covers_year"`
	CoversMonth            int16     `json:"covers_month"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
}

func (q *Queries) GetPaymentHistory(ctx context.Context, memberNumber int32) ([]GetPaymentHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPaymentHistory, memberNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentHistoryRow
	for rows.Next() {
		var i GetPaymentHistoryRow
		if err := rows.Scan(
			&i.CoversYear,
			&i.CoversMonth,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.ProcessedTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentWaiver = `-- name: GetPaymentWaiver :one
SELECT covers_year, covers_month, reason, created_at
FROM payment_waivers
WHERE member_number = $1
  AND covers_year = $2
  AND covers_month = $3
`

type GetPaymentWaiverParams struct {
	MemberNumber int32 `json:"member_number"`
	CoversYear   int32 `json:"covers_year"`
	CoversMonth  int16 `json:"covers_month"`
}

type GetPaymentWaiverRow struct {
	CoversYear  int32     `json:"covers_year"`
	CoversMonth int16     `json:"covers_month"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetPaymentWaiver(ctx context.Context, arg GetPaymentWaiverParams) (GetPaymentWaiverRow, error) {
	row := q.db.QueryRow(ctx, getPaymentWaiver, arg.MemberNumber, arg.CoversYear, arg.CoversMonth)
	var i GetPaymentWaiverRow
	err := row.Scan(
		&i.CoversYear,
		&i.CoversMonth,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalBalance = `-- name: GetTotalBalance :many
SELECT currency, COALESCE(SUM(balance), 0)::numeric AS total
FROM bank_accounts
WHERE deleted_at IS NULL AND balance IS NOT NULL
GROUP BY currency
ORDER BY currency
`

type GetTotalBalanceRow struct {
	Currency string `json:"currency"`
	Total    string `json:"total"`
}

// Backs the Budget page's "Current Balance" figure (GET
// /transactions/summary) — summed across every non-soft-deleted account,
// grouped by currency (don't assume single-currency, same as
// GetTransactionCategorySummary). An account with no balance yet (never
// successfully synced) is excluded from the sum entirely rather than
// counted as zero, so a not-yet-synced account can't understate the total —
// revisit if that instead reads as confusingly incomplete.
// COALESCE forces this NOT NULL (same reason GetTransactionCategorySummary
// does it) — SUM() is nullable to Postgres's planner regardless of the WHERE
// filter guaranteeing a non-null result here, and sqlc maps a nullable
// numeric to pgtype.Numeric instead of the plain-string override.
func (q *Queries) GetTotalBalance(ctx context.Context) ([]GetTotalBalanceRow, error) {
	rows, err := q.db.Query(ctx, getTotalBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalBalanceRow
	for rows.Next() {
		var i GetTotalBalanceRow
		if err := rows.Scan(&i.Currency, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionCategorySummary = `-- name: GetTransactionCategorySummary :many
SELECT
    pt.direction,
    pt.category,
    rt.currency,
    COALESCE(SUM(ABS(rt.amount)), 0)::numeric AS total
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.category != 'internal_transfer'
  AND ($1::date IS NULL OR rt.transaction_date >= $1::date)
  AND ($2::date IS NULL OR rt.transaction_date <= $2::date)
GROUP BY pt.direction, pt.category, rt.currency
ORDER BY pt.direction, total DESC
`

type GetTransactionCategorySummaryParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type GetTransactionCategorySummaryRow struct {
	Direction string `json:"direction"`
	Category  string `json:"category"`
	Currency  string `json:"currency"`
	Total     string `json:"total"`
}

// Budgeting view:
// totals grouped by direction/category/currency only — no member_number, no
// counterparty, no per-transaction rows, so this is safe for the
// widely-held view-budget role (unlike ListTransactions). SUM(ABS(amount))
// so an "outgoing" total reads as a positive spend figure rather than the
// signed value raw_transactions stores it as. internal_transfer excluded
// entirely — money moving between our own bank_accounts isn't real income or
// expense and would otherwise inflate both totals for the same transfer.
func (q *Queries) GetTransactionCategorySummary(ctx context.Context, arg GetTransactionCategorySummaryParams) ([]GetTransactionCategorySummaryRow, error) {
	rows, err := q.db.Query(ctx, getTransactionCategorySummary, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionCategorySummaryRow
	for rows.Next() {
		var i GetTransactionCategorySummaryRow
		if err := rows.Scan(
			&i.Direction,
			&i.Category,
			&i.Currency,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionDetail = `-- name: GetTransactionDetail :one
SELECT
    pt.id,
    rt.transaction_date,
    rt.amount,
    rt.currency,
    pt.direction,
    pt.category,
    pt.member_number,
    pt.matched_by,
    pt.is_public_visible,
    rt.variable_symbol,
    rt.specific_symbol,
    rt.constant_symbol,
    rt.counter_account_number,
    rt.counter_account_name,
    rt.message_for_recipient,
    rt.user_identification,
    rt.comment,
    pt.admin_comment
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.id = $1
`

type GetTransactionDetailRow struct {
	ID                   int64     `json:"id"`
	TransactionDate      time.Time `json:"transaction_date"`
	Amount               string    `json:"amount"`
	Currency             string    `json:"currency"`
	Direction            string    `json:"direction"`
	Category             string    `json:"category"`
	MemberNumber         *int32    `json:"member_number"`
	MatchedBy            *string   `json:"matched_by"`
	IsPublicVisible      bool      `json:"is_public_visible"`
	VariableSymbol       *string   `json:"variable_symbol"`
	SpecificSymbol       *string   `json:"specific_symbol"`
	ConstantSymbol       *string   `json:"constant_symbol"`
	CounterAccountNumber *string   `json:"counter_account_number"`
	CounterAccountName   *string   `json:"counter_account_name"`
	MessageForRecipient  *string   `json:"message_for_recipient"`
	UserIdentification   *string   `json:"user_identification"`
	Comment              *string   `json:"comment"`
	AdminComment         *string   `json:"admin_comment"`
}

// One row for the transaction browser's detail / edit view — same columns as
// ListTransactions minus the window count. Covered months come from
// ListCoverageForTransaction.
func (q *Queries) GetTransactionDetail(ctx context.Context, id int64) (GetTransactionDetailRow, error) {
	row := q.db.QueryRow(ctx, getTransactionDetail, id)
	var i GetTransactionDetailRow
	err := row.Scan(
		&i.ID,
		&i.TransactionDate,
		&i.Amount,
		&i.Currency,
		&i.Direction,
		&i.Category,
		&i.MemberNumber,
		&i.MatchedBy,
		&i.IsPublicVisible,
		&i.VariableSymbol,
		&i.SpecificSymbol,
		&i.ConstantSymbol,
		&i.CounterAccountNumber,
		&i.CounterAccountName,
		&i.MessageForRecipient,
		&i.UserIdentification,
		&i.Comment,
		&i.AdminComment,
	)
	return i, err
}

const insertCoverageRow = `-- name: InsertCoverageRow :execrows
INSERT INTO payment_coverage (processed_transaction_id, member_number, covers_year, covers_month)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_number, covers_year, covers_month) DO NOTHING
`

type InsertCoverageRowParams struct {
	ProcessedTransactionID int64 `json:"processed_transaction_id"`
	MemberNumber           int32 `json:"member_number"`
	CoversYear             int32 `json:"covers_year"`
	CoversMonth            int16 `json:"covers_month"`
}

// ON CONFLICT DO NOTHING + :execrows so the caller can tell which requested
// month was already covered by a *different* transaction (0 rows affected) and
// report it, rather than silently dropping it.
func (q *Queries) InsertCoverageRow(ctx context.Context, arg InsertCoverageRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCoverageRow,
		arg.ProcessedTransactionID,
		arg.MemberNumber,
		arg.CoversYear,
		arg.CoversMonth,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertRawTransaction = `-- name: InsertRawTransaction :execrows
INSERT INTO raw_transactions (
    bank_account_id, fio_transaction_id, transaction_date, amount, currency,
    counter_account_number, counter_account_name, counter_bank_code, counter_bank_name, bic,
    variable_symbol, specific_symbol, constant_symbol,
    user_identification, message_for_recipient, transaction_type, executor, specification, comment, instruction_id,
    raw_payload
) VALUES (
    $1,
    $2,
    $3,
    $4::numeric,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
ON CONFLICT (bank_account_id, fio_transaction_id) DO NOTHING
`

type InsertRawTransactionParams struct {
	BankAccountID        int32     `json:"bank_account_id"`
	FioTransactionID     int64     `json:"fio_transaction_id"`
	TransactionDate      time.Time `json:"transaction_date"`
	Amount               string    `json:"amount"`
	Currency             string    `json:"currency"`
	CounterAccountNumber *string   `json:"counter_account_number"`
	CounterAccountName   *string   `json:"counter_account_name"`
	CounterBankCode      *string   `json:"counter_bank_code"`
	CounterBankName      *string   `json:"counter_bank_name"`
	Bic                  *string   `json:"bic"`
	VariableSymbol       *string   `json:"variable_symbol"`
	SpecificSymbol       *string   `json:"specific_symbol"`
	ConstantSymbol       *string   `json:"constant_symbol"`
	UserIdentification   *string   `json:"user_identification"`
	MessageForRecipient  *string   `json:"message_for_recipient"`
	TransactionType      *string   `json:"transaction_type"`
	Executor             *string   `json:"executor"`
	Specification        *string   `json:"specification"`
	Comment              *string   `json:"comment"`
	InstructionID        *string   `json:"instruction_id"`
	RawPayload           []byte    `json:"raw_payload"`
}

func (q *Queries) InsertRawTransaction(ctx context.Context, arg InsertRawTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawTransaction,
		arg.BankAccountID,
		arg.FioTransactionID,
		arg.TransactionDate,
		arg.Amount,
		arg.Currency,
		arg.CounterAccountNumber,
		arg.CounterAccountName,
		arg.CounterBankCode,
		arg.CounterBankName,
		arg.Bic,
		arg.VariableSymbol,
		arg.SpecificSymbol,
		arg.ConstantSymbol,
		arg.UserIdentification,
		arg.MessageForRecipient,
		arg.TransactionType,
		arg.Executor,
		arg.Specification,
		arg.Comment,
		arg.InstructionID,
		arg.RawPayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveBankAccountNumbers = `-- name: ListActiveBankAccountNumbers :many
SELECT fio_account_id FROM bank_accounts WHERE deleted_at IS NULL
`

// Internal use only (processing.go, self-transfer detection) — the account
// numbers of every non-soft-deleted bank account we hold, so a transaction
// whose counterparty is one of these can be recognized as a transfer between
// our own accounts rather than real income/expense. Soft-deleted accounts
// excluded deliberately: no live account there to be the other leg of a
// current transfer.
func (q *Queries) ListActiveBankAccountNumbers(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveBankAccountNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fio_account_id string
		if err := rows.Scan(&fio_account_id); err != nil {
			return nil, err
		}
		items = append(items, fio_account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, fio_account_id, iban, currency, display_name, created_at,
       (fio_token_encrypted IS NOT NULL)::boolean AS has_token,
       (deleted_at IS NULL)::boolean AS is_active,
       balance, balance_as_of
FROM bank_accounts ORDER BY id
`

type ListBankAccountsRow struct {
	ID           int32              `json:"id"`
	FioAccountID string             `json:"fio_account_id"`
	Iban         *string            `json:"iban"`
	Currency     string             `json:"currency"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    time.Time          `json:"created_at"`
	HasToken     bool               `json:"has_token"`
	IsActive     bool               `json:"is_active"`
	Balance      pgtype.Numeric     `json:"balance"`
	BalanceAsOf  pgtype.Timestamptz `json:"balance_as_of"`
}

// Admin-facing list (GET /account) — deliberately excludes the Fio token.
// Includes soft-deleted accounts (is_active = false) so admins still see them
// in the UI, crossed out, as a record that the account used to exist. For the
// token itself, see ListBankAccountsWithToken (internal use only). balance/
// balance_as_of are both null until the account's first successful sync
// (see UpdateBankAccountBalance) — nullable numeric/timestamptz fall back to
// pgtype.Numeric/pgtype.Timestamptz rather than the plain-string/time.Time
// sqlc overrides (those only apply to NOT NULL columns), so the handler
// converts them to nullable JSON strings itself.
func (q *Queries) ListBankAccounts(ctx context.Context) ([]ListBankAccountsRow, error) {
	rows, err := q.db.Query(ctx, listBankAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountsRow
	for rows.Next() {
		var i ListBankAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.FioAccountID,
			&i.Iban,
			&i.Currency,
			&i.DisplayName,
			&i.CreatedAt,
			&i.HasToken,
			&i.IsActive,
			&i.Balance,
			&i.BalanceAsOf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccountsWithToken = `-- name: ListBankAccountsWithToken :many
SELECT id, fio_account_id, iban, currency, display_name, created_at,
       pgp_sym_decrypt(fio_token_encrypted, $1::text) AS fio_token,
       (deleted_at IS NULL)::boolean AS is_active
FROM bank_accounts ORDER BY id
`

type ListBankAccountsWithTokenRow struct {
	ID           int32     `json:"id"`
	FioAccountID string    `json:"fio_account_id"`
	Iban         *string   `json:"iban"`
	Currency     string    `json:"currency"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	FioToken     string    `json:"fio_token"`
	IsActive     bool      `json:"is_active"`
}

// Internal use only (the Fio sync job) — includes the decrypted Fio token.
// Includes soft-deleted accounts (is_active = false); the sync job itself is
// responsible for skipping those rather than filtering here, since "should
// this account sync" is business logic, not a storage-layer concern. Never
// expose this query's result over HTTP. encryption_key is bound as a query
// parameter via pgp_sym_decrypt, never interpolated into SQL text. fio_token
// is NULL for any account not yet backfilled with a token.
func (q *Queries) ListBankAccountsWithToken(ctx context.Context, encryptionKey string) ([]ListBankAccountsWithTokenRow, error) {
	rows, err := q.db.Query(ctx, listBankAccountsWithToken, encryptionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountsWithTokenRow
	for rows.Next() {
		var i ListBankAccountsWithTokenRow
		if err := rows.Scan(
			&i.ID,
			&i.FioAccountID,
			&i.Iban,
			&i.Currency,
			&i.DisplayName,
			&i.CreatedAt,
			&i.FioToken,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT name, is_mandatory, created_at FROM transaction_categories ORDER BY is_mandatory DESC, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]TransactionCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionCategory
	for rows.Next() {
		var i TransactionCategory
		if err := rows.Scan(&i.Name, &i.IsMandatory, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentedTransactionsInMonth = `-- name: ListCommentedTransactionsInMonth :many
SELECT pt.member_number, pt.id AS processed_transaction_id, rt.transaction_date,
       rt.amount, rt.currency, pt.admin_comment
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.member_number IS NOT NULL
  AND pt.admin_comment IS NOT NULL
  AND date_trunc('month', rt.transaction_date::timestamp)
        = make_date($1::int, $2::int, 1)::timestamp
ORDER BY rt.transaction_date, pt.id
`

type ListCommentedTransactionsInMonthParams struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

type ListCommentedTransactionsInMonthRow struct {
	MemberNumber           *int32    `json:"member_number"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	AdminComment           *string   `json:"admin_comment"`
}

// Backs GET /payments/{year}/{month}/commented — every commented
// (admin_comment IS NOT NULL) transaction matched to a member, dated in the
// given month, regardless of whether that member is otherwise missing a
// payment. Deliberately a separate endpoint/query from
// ListMembersMissingPayment rather than folded into it — keeps "missing"
// meaning strictly "no coverage row" and lets the caller (Orca) merge the
// two client-side by member_number.
func (q *Queries) ListCommentedTransactionsInMonth(ctx context.Context, arg ListCommentedTransactionsInMonthParams) ([]ListCommentedTransactionsInMonthRow, error) {
	rows, err := q.db.Query(ctx, listCommentedTransactionsInMonth, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentedTransactionsInMonthRow
	for rows.Next() {
		var i ListCommentedTransactionsInMonthRow
		if err := rows.Scan(
			&i.MemberNumber,
			&i.ProcessedTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.AdminComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentedTransactionsInMonthForWorkplace = `-- name: ListCommentedTransactionsInMonthForWorkplace :many
SELECT pt.member_number, pt.id AS processed_transaction_id, rt.transaction_date,
       rt.amount, rt.currency, pt.admin_comment
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
JOIN members m ON m.member_number = pt.member_number
WHERE m.workplace_executive_committee_sub = ANY($1::uuid[])
  AND pt.admin_comment IS NOT NULL
  AND date_trunc('month', rt.transaction_date::timestamp)
        = make_date($2::int, $3::int, 1)::timestamp
ORDER BY rt.transaction_date, pt.id
`

type ListCommentedTransactionsInMonthForWorkplaceParams struct {
	WorkplaceSubs []pgtype.UUID `json:"workplace_subs"`
	Year          int32         `json:"year"`
	Month         int32         `json:"month"`
}

type ListCommentedTransactionsInMonthForWorkplaceRow struct {
	MemberNumber           *int32    `json:"member_number"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	AdminComment           *string   `json:"admin_comment"`
}

// Backs GET /payments/workplace/{year}/{month}/commented — see
// ListCommentedTransactionsInMonth, scoped to the caller's workplace group(s)
// the same way ListMembersMissingPaymentForWorkplace is.
func (q *Queries) ListCommentedTransactionsInMonthForWorkplace(ctx context.Context, arg ListCommentedTransactionsInMonthForWorkplaceParams) ([]ListCommentedTransactionsInMonthForWorkplaceRow, error) {
	rows, err := q.db.Query(ctx, listCommentedTransactionsInMonthForWorkplace, arg.WorkplaceSubs, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentedTransactionsInMonthForWorkplaceRow
	for rows.Next() {
		var i ListCommentedTransactionsInMonthForWorkplaceRow
		if err := rows.Scan(
			&i.MemberNumber,
			&i.ProcessedTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.AdminComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentedTransactionsInYear = `-- name: ListCommentedTransactionsInYear :many
SELECT pt.member_number, pt.id AS processed_transaction_id, rt.transaction_date,
       rt.amount, rt.currency, pt.admin_comment
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.member_number IS NOT NULL
  AND pt.admin_comment IS NOT NULL
  AND EXTRACT(YEAR FROM rt.transaction_date::timestamp)::int = $1::int
ORDER BY rt.transaction_date, pt.id
`

type ListCommentedTransactionsInYearRow struct {
	MemberNumber           *int32    `json:"member_number"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	AdminComment           *string   `json:"admin_comment"`
}

// Backs GET /payments/{year}/commented — see ListCommentedTransactionsInMonth,
// year-scoped instead of month-scoped.
func (q *Queries) ListCommentedTransactionsInYear(ctx context.Context, year int32) ([]ListCommentedTransactionsInYearRow, error) {
	rows, err := q.db.Query(ctx, listCommentedTransactionsInYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentedTransactionsInYearRow
	for rows.Next() {
		var i ListCommentedTransactionsInYearRow
		if err := rows.Scan(
			&i.MemberNumber,
			&i.ProcessedTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.AdminComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentedTransactionsInYearForWorkplace = `-- name: ListCommentedTransactionsInYearForWorkplace :many
SELECT pt.member_number, pt.id AS processed_transaction_id, rt.transaction_date,
       rt.amount, rt.currency, pt.admin_comment
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
JOIN members m ON m.member_number = pt.member_number
WHERE m.workplace_executive_committee_sub = ANY($1::uuid[])
  AND pt.admin_comment IS NOT NULL
  AND EXTRACT(YEAR FROM rt.transaction_date::timestamp)::int = $2::int
ORDER BY rt.transaction_date, pt.id
`

type ListCommentedTransactionsInYearForWorkplaceParams struct {
	WorkplaceSubs []pgtype.UUID `json:"workplace_subs"`
	Year          int32         `json:"year"`
}

type ListCommentedTransactionsInYearForWorkplaceRow struct {
	MemberNumber           *int32    `json:"member_number"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	AdminComment           *string   `json:"admin_comment"`
}

// Backs GET /payments/workplace/{year}/commented — see
// ListCommentedTransactionsInMonthForWorkplace, year-scoped instead of
// month-scoped.
func (q *Queries) ListCommentedTransactionsInYearForWorkplace(ctx context.Context, arg ListCommentedTransactionsInYearForWorkplaceParams) ([]ListCommentedTransactionsInYearForWorkplaceRow, error) {
	rows, err := q.db.Query(ctx, listCommentedTransactionsInYearForWorkplace, arg.WorkplaceSubs, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentedTransactionsInYearForWorkplaceRow
	for rows.Next() {
		var i ListCommentedTransactionsInYearForWorkplaceRow
		if err := rows.Scan(
			&i.MemberNumber,
			&i.ProcessedTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.AdminComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoverageForTransaction = `-- name: ListCoverageForTransaction :many
SELECT covers_year, covers_month
FROM payment_coverage
WHERE processed_transaction_id = $1
ORDER BY covers_year, covers_month
`

type ListCoverageForTransactionRow struct {
	CoversYear  int32 `json:"covers_year"`
	CoversMonth int16 `json:"covers_month"`
}

func (q *Queries) ListCoverageForTransaction(ctx context.Context, processedTransactionID int64) ([]ListCoverageForTransactionRow, error) {
	rows, err := q.db.Query(ctx, listCoverageForTransaction, processedTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCoverageForTransactionRow
	for rows.Next() {
		var i ListCoverageForTransactionRow
		if err := rows.Scan(&i.CoversYear, &i.CoversMonth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventLogs = `-- name: ListEventLogs :many
SELECT event_type, id, started_at, finished_at, status, detail, fetched, processed, error_message, count(*) OVER () AS total_count
FROM (
    SELECT
        'fio_sync'::text AS event_type,
        sfr.id,
        sfr.started_at,
        sfr.finished_at,
        sfr.status,
        ba.display_name AS detail,
        sfr.transactions_fetched AS fetched,
        sfr.transactions_inserted AS processed,
        sfr.error_message
    FROM sync_fio_runs sfr
    LEFT JOIN bank_accounts ba ON ba.id = sfr.bank_account_id
    UNION ALL
    SELECT
        'orca_sync'::text AS event_type,
        sor.id,
        sor.started_at,
        sor.finished_at,
        sor.status,
        NULL::text AS detail,
        sor.members_fetched AS fetched,
        sor.members_upserted AS processed,
        sor.error_message
    FROM sync_orca_runs sor
) events
ORDER BY started_at DESC, id DESC
LIMIT $2::int OFFSET $1::int
`

type ListEventLogsParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

type ListEventLogsRow struct {
	EventType    string             `json:"event_type"`
	ID           int64              `json:"id"`
	StartedAt    time.Time          `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Status       string             `json:"status"`
	Detail       *string            `json:"detail"`
	Fetched      *int32             `json:"fetched"`
	Processed    *int32             `json:"processed"`
	ErrorMessage *string            `json:"error_message"`
	TotalCount   int64              `json:"total_count"`
}

// Admin event log (GET /event-logs): sync_fio_runs and sync_orca_runs merged
// into one feed, newest first. No filters — just a simple paged log, same
// limit/offset + count(*) OVER () pagination pattern as ListTransactions.
// detail is the bank account's display name for a fio_sync row, NULL for
// orca_sync (there's no per-account breakdown for the member sync).
func (q *Queries) ListEventLogs(ctx context.Context, arg ListEventLogsParams) ([]ListEventLogsRow, error) {
	rows, err := q.db.Query(ctx, listEventLogs, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventLogsRow
	for rows.Next() {
		var i ListEventLogsRow
		if err := rows.Scan(
			&i.EventType,
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Detail,
			&i.Fetched,
			&i.Processed,
			&i.ErrorMessage,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalTransferCandidates = `-- name: ListInternalTransferCandidates :many
SELECT pt.id
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.category != 'internal_transfer'
  AND (pt.matched_by IS NULL OR pt.matched_by != 'manual')
  AND rt.counter_account_number = ANY($1::text[])
`

// Rows categorized before their counterparty's bank_accounts row existed —
// internal-transfer detection (processing.go) only ever sees the roster as
// of the moment a transaction was first processed, and a processed row is
// never revisited on its own (see ListUnprocessedTransactions), so adding a
// second/new account later leaves earlier transfers to/from it permanently
// miscategorized. Excludes matched_by = 'manual' — never silently override
// an admin's explicit decision, same rule as elsewhere in this schema (see
// payment_waivers, admin_comment). Excludes already-internal_transfer rows
// so a repeat run only touches what's still wrong.
func (q *Queries) ListInternalTransferCandidates(ctx context.Context, accountNumbers []string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listInternalTransferCandidates, accountNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersMissingPayment = `-- name: ListMembersMissingPayment :many
SELECT ma.member_number, ma.total_missed_months, ma.has_ever_paid
FROM member_arrears ma
JOIN members m ON m.member_number = ma.member_number
WHERE date_trunc('month', m.fee_start_date::timestamp)
        <= make_date($1::int, $2::int, 1)::timestamp
  AND make_date($1::int, $2::int, 1)::timestamp
        <= LEAST(
             date_trunc('month', COALESCE(m.fee_stop_date, CURRENT_DATE)::timestamp),
             date_trunc('month', CURRENT_DATE::timestamp) - interval '2 months'
           )
  AND NOT EXISTS (
      SELECT 1 FROM payment_coverage pc
      WHERE pc.member_number = ma.member_number
        AND pc.covers_year = $1::int
        AND pc.covers_month = $2::int
  )
  AND NOT EXISTS (
      SELECT 1 FROM payment_waivers pw
      WHERE pw.member_number = ma.member_number
        AND pw.covers_year = $1::int
        AND pw.covers_month = $2::int
  )
ORDER BY ma.total_missed_months DESC, ma.member_number
`

type ListMembersMissingPaymentParams struct {
	Year  int32 `json:"year"`
	Month int32 `json:"month"`
}

// Members who were liable for the membership fee in the given year/month but
// have no payment_coverage row for it. "Liable" = fee_start_date is set (the
// member_arrears view enforces this) and the target month falls within
// [fee_start_date, upper bound] at month granularity, where upper bound is
// COALESCE(fee_stop_date, CURRENT_DATE) capped at CURRENT_DATE - 2 months: dues
// for month M are due by the end of month M+1 (a recurring one-month grace,
// not just onboarding),
// so M only counts as liable-and-overdue once M+1 has also fully elapsed.
//
// total_missed_months comes from the member_arrears view: a total-arrears figure
// independent of the queried month (every unpaid month across the member's full
// liability window). Always >= 1 here, since the queried month is one of them.
// has_ever_paid (also from member_arrears) is false for a member with zero
// payment_coverage rows ever — distinguishes "never started paying" from
// "usually pays, missed a month" for follow-up prioritization.
// Rows are ordered by it descending ("top offenders first"), member_number
// breaking ties.
func (q *Queries) ListMembersMissingPayment(ctx context.Context, arg ListMembersMissingPaymentParams) ([]MemberArrear, error) {
	rows, err := q.db.Query(ctx, listMembersMissingPayment, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberArrear
	for rows.Next() {
		var i MemberArrear
		if err := rows.Scan(&i.MemberNumber, &i.TotalMissedMonths, &i.HasEverPaid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersMissingPaymentForWorkplace = `-- name: ListMembersMissingPaymentForWorkplace :many
SELECT ma.member_number, ma.total_missed_months, ma.has_ever_paid
FROM member_arrears ma
JOIN members m ON m.member_number = ma.member_number
WHERE m.workplace_executive_committee_sub = ANY($1::uuid[])
  AND date_trunc('month', m.fee_start_date::timestamp)
        <= make_date($2::int, $3::int, 1)::timestamp
  AND make_date($2::int, $3::int, 1)::timestamp
        <= LEAST(
             date_trunc('month', COALESCE(m.fee_stop_date, CURRENT_DATE)::timestamp),
             date_trunc('month', CURRENT_DATE::timestamp) - interval '2 months'
           )
  AND NOT EXISTS (
      SELECT 1 FROM payment_coverage pc
      WHERE pc.member_number = ma.member_number
        AND pc.covers_year = $2::int
        AND pc.covers_month = $3::int
  )
  AND NOT EXISTS (
      SELECT 1 FROM payment_waivers pw
      WHERE pw.member_number = ma.member_number
        AND pw.covers_year = $2::int
        AND pw.covers_month = $3::int
  )
ORDER BY ma.total_missed_months DESC, ma.member_number
`

type ListMembersMissingPaymentForWorkplaceParams struct {
	WorkplaceSubs []pgtype.UUID `json:"workplace_subs"`
	Year          int32         `json:"year"`
	Month         int32         `json:"month"`
}

// Workplace-rep counterpart to ListMembersMissingPayment — same shape and
// logic, scoped to members in any of the caller's workplace groups instead of
// every member. See that query's comment for the liability-window logic.
func (q *Queries) ListMembersMissingPaymentForWorkplace(ctx context.Context, arg ListMembersMissingPaymentForWorkplaceParams) ([]MemberArrear, error) {
	rows, err := q.db.Query(ctx, listMembersMissingPaymentForWorkplace, arg.WorkplaceSubs, arg.Year, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberArrear
	for rows.Next() {
		var i MemberArrear
		if err := rows.Scan(&i.MemberNumber, &i.TotalMissedMonths, &i.HasEverPaid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersMissingPaymentInYear = `-- name: ListMembersMissingPaymentInYear :many
SELECT ma.member_number, ma.total_missed_months, ma.has_ever_paid
FROM member_arrears ma
JOIN members m ON m.member_number = ma.member_number
WHERE EXISTS (
    SELECT 1
    FROM generate_series(
        greatest(
            date_trunc('month', m.fee_start_date::timestamp),
            make_date($1::int, 1, 1)::timestamp
        ),
        least(
            date_trunc('month', COALESCE(m.fee_stop_date, CURRENT_DATE)::timestamp),
            date_trunc('month', CURRENT_DATE::timestamp) - interval '2 months',
            make_date($1::int, 12, 1)::timestamp
        ),
        interval '1 month'
    ) AS ym(month)
    WHERE NOT EXISTS (
        SELECT 1 FROM payment_coverage pc
        WHERE pc.member_number = ma.member_number
          AND pc.covers_year = EXTRACT(YEAR FROM ym.month)::int
          AND pc.covers_month = EXTRACT(MONTH FROM ym.month)::int
    )
    AND NOT EXISTS (
        SELECT 1 FROM payment_waivers pw
        WHERE pw.member_number = ma.member_number
          AND pw.covers_year = EXTRACT(YEAR FROM ym.month)::int
          AND pw.covers_month = EXTRACT(MONTH FROM ym.month)::int
    )
)
ORDER BY ma.total_missed_months DESC, ma.member_number
`

// Members who missed at least one liable month during the given calendar year —
// the whole-year counterpart of ListMembersMissingPayment. Same
// {member_number, total_missed_months, has_ever_paid} shape and ordering;
// total_missed_months/has_ever_paid are still the full-liability-window
// figures (member_arrears view), not scoped to the year.
func (q *Queries) ListMembersMissingPaymentInYear(ctx context.Context, year int32) ([]MemberArrear, error) {
	rows, err := q.db.Query(ctx, listMembersMissingPaymentInYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberArrear
	for rows.Next() {
		var i MemberArrear
		if err := rows.Scan(&i.MemberNumber, &i.TotalMissedMonths, &i.HasEverPaid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersMissingPaymentInYearForWorkplace = `-- name: ListMembersMissingPaymentInYearForWorkplace :many
SELECT ma.member_number, ma.total_missed_months, ma.has_ever_paid
FROM member_arrears ma
JOIN members m ON m.member_number = ma.member_number
WHERE m.workplace_executive_committee_sub = ANY($1::uuid[])
  AND EXISTS (
    SELECT 1
    FROM generate_series(
        greatest(
            date_trunc('month', m.fee_start_date::timestamp),
            make_date($2::int, 1, 1)::timestamp
        ),
        least(
            date_trunc('month', COALESCE(m.fee_stop_date, CURRENT_DATE)::timestamp),
            date_trunc('month', CURRENT_DATE::timestamp) - interval '2 months',
            make_date($2::int, 12, 1)::timestamp
        ),
        interval '1 month'
    ) AS ym(month)
    WHERE NOT EXISTS (
        SELECT 1 FROM payment_coverage pc
        WHERE pc.member_number = ma.member_number
          AND pc.covers_year = EXTRACT(YEAR FROM ym.month)::int
          AND pc.covers_month = EXTRACT(MONTH FROM ym.month)::int
    )
    AND NOT EXISTS (
        SELECT 1 FROM payment_waivers pw
        WHERE pw.member_number = ma.member_number
          AND pw.covers_year = EXTRACT(YEAR FROM ym.month)::int
          AND pw.covers_month = EXTRACT(MONTH FROM ym.month)::int
    )
)
ORDER BY ma.total_missed_months DESC, ma.member_number
`

type ListMembersMissingPaymentInYearForWorkplaceParams struct {
	WorkplaceSubs []pgtype.UUID `json:"workplace_subs"`
	Year          int32         `json:"year"`
}

// Workplace-rep counterpart to ListMembersMissingPaymentInYear — same shape
// and logic, scoped to members in any of the caller's workplace groups.
func (q *Queries) ListMembersMissingPaymentInYearForWorkplace(ctx context.Context, arg ListMembersMissingPaymentInYearForWorkplaceParams) ([]MemberArrear, error) {
	rows, err := q.db.Query(ctx, listMembersMissingPaymentInYearForWorkplace, arg.WorkplaceSubs, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberArrear
	for rows.Next() {
		var i MemberArrear
		if err := rows.Scan(&i.MemberNumber, &i.TotalMissedMonths, &i.HasEverPaid); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRematchCandidates = `-- name: ListRematchCandidates :many
SELECT pt.id, rt.variable_symbol, rt.transaction_date
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pt.member_number IS NULL
  AND pt.category != 'internal_transfer'
  AND (pt.matched_by IS NULL OR pt.matched_by != 'manual')
  AND rt.variable_symbol IS NOT NULL AND rt.variable_symbol != ''
`

type ListRematchCandidatesRow struct {
	ID              int64     `json:"id"`
	VariableSymbol  *string   `json:"variable_symbol"`
	TransactionDate time.Time `json:"transaction_date"`
}

// Backs POST /processing/run action=rematch_unmatched — currently-unmatched
// processed transactions worth re-checking against member_payment_identifiers,
// for when a member's liability window was wrong at original processing time
// (a bad fee_start_date pulled from Orca) and has since been corrected
// upstream and re-synced (see "Orca member sync"). Skips
// matched_by = 'manual' (never override an admin's explicit decision, same
// rule as elsewhere in this schema) and category = 'internal_transfer' (that
// precedence is fixed by processOne, not up for re-evaluation here — see
// ReclassifyInternalTransfers for the transfer side of the same idea).
// member_number IS NULL already implies matched_by IS NULL in practice
// (matched_by is only ever set alongside a member_number) — the explicit
// matched_by check is just defensive.
func (q *Queries) ListRematchCandidates(ctx context.Context) ([]ListRematchCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listRematchCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRematchCandidatesRow
	for rows.Next() {
		var i ListRematchCandidatesRow
		if err := rows.Scan(&i.ID, &i.VariableSymbol, &i.TransactionDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT
    pt.id,
    rt.transaction_date,
    rt.amount,
    rt.currency,
    pt.direction,
    pt.category,
    pt.member_number,
    pt.matched_by,
    pt.is_public_visible,
    rt.variable_symbol,
    rt.specific_symbol,
    rt.constant_symbol,
    rt.counter_account_number,
    rt.counter_account_name,
    rt.message_for_recipient,
    rt.user_identification,
    rt.comment,
    pt.admin_comment,
    count(*) OVER () AS total_count
FROM processed_transactions pt
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE ($1::boolean IS NULL
        OR (pt.member_number IS NOT NULL) = $1::boolean)
  AND ($2::text IS NULL OR pt.direction = $2::text)
  AND ($3::text IS NULL OR pt.category = $3::text)
  AND ($4::text IS NULL OR pt.matched_by = $4::text)
  AND ($5::int IS NULL OR pt.member_number = $5::int)
  AND ($6::date IS NULL OR rt.transaction_date >= $6::date)
  AND ($7::date IS NULL OR rt.transaction_date <= $7::date)
  AND ($8::text IS NULL OR (
        rt.counter_account_name ILIKE '%' || $8::text || '%'
        OR rt.counter_account_number ILIKE '%' || $8::text || '%'
        OR rt.message_for_recipient ILIKE '%' || $8::text || '%'
        OR rt.comment ILIKE '%' || $8::text || '%'
      ))
ORDER BY rt.transaction_date DESC, rt.id DESC
LIMIT $10::int OFFSET $9::int
`

type ListTransactionsParams struct {
	Assigned     *bool       `json:"assigned"`
	Direction    *string     `json:"direction"`
	Category     *string     `json:"category"`
	MatchedBy    *string     `json:"matched_by"`
	MemberNumber *int32      `json:"member_number"`
	DateFrom     pgtype.Date `json:"date_from"`
	DateTo       pgtype.Date `json:"date_to"`
	Search       *string     `json:"search"`
	Off          int32       `json:"off"`
	Lim          int32       `json:"lim"`
}

type ListTransactionsRow struct {
	ID                   int64     `json:"id"`
	TransactionDate      time.Time `json:"transaction_date"`
	Amount               string    `json:"amount"`
	Currency             string    `json:"currency"`
	Direction            string    `json:"direction"`
	Category             string    `json:"category"`
	MemberNumber         *int32    `json:"member_number"`
	MatchedBy            *string   `json:"matched_by"`
	IsPublicVisible      bool      `json:"is_public_visible"`
	VariableSymbol       *string   `json:"variable_symbol"`
	SpecificSymbol       *string   `json:"specific_symbol"`
	ConstantSymbol       *string   `json:"constant_symbol"`
	CounterAccountNumber *string   `json:"counter_account_number"`
	CounterAccountName   *string   `json:"counter_account_name"`
	MessageForRecipient  *string   `json:"message_for_recipient"`
	UserIdentification   *string   `json:"user_identification"`
	Comment              *string   `json:"comment"`
	AdminComment         *string   `json:"admin_comment"`
	TotalCount           int64     `json:"total_count"`
}

// Admin transaction browser: processed_transactions enriched with their
// raw_transactions row, with optional filters. Every filter arg is nullable —
// NULL / omitted means "don't filter on this". total_count is the full match
// count ignoring LIMIT/OFFSET (window aggregate) so the caller can paginate.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.Assigned,
		arg.Direction,
		arg.Category,
		arg.MatchedBy,
		arg.MemberNumber,
		arg.DateFrom,
		arg.DateTo,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.Direction,
			&i.Category,
			&i.MemberNumber,
			&i.MatchedBy,
			&i.IsPublicVisible,
			&i.VariableSymbol,
			&i.SpecificSymbol,
			&i.ConstantSymbol,
			&i.CounterAccountNumber,
			&i.CounterAccountName,
			&i.MessageForRecipient,
			&i.UserIdentification,
			&i.Comment,
			&i.AdminComment,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedTransactions = `-- name: ListUnprocessedTransactions :many
SELECT rt.id, rt.bank_account_id, rt.fio_transaction_id, rt.transaction_date, rt.amount, rt.currency, rt.counter_account_number, rt.counter_account_name, rt.counter_bank_code, rt.counter_bank_name, rt.bic, rt.variable_symbol, rt.specific_symbol, rt.constant_symbol, rt.user_identification, rt.message_for_recipient, rt.transaction_type, rt.executor, rt.specification, rt.comment, rt.instruction_id, rt.raw_payload, rt.synced_at FROM raw_transactions rt
LEFT JOIN processed_transactions pt ON pt.raw_transaction_id = rt.id
WHERE pt.id IS NULL
ORDER BY rt.id
`

func (q *Queries) ListUnprocessedTransactions(ctx context.Context) ([]RawTransaction, error) {
	rows, err := q.db.Query(ctx, listUnprocessedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawTransaction
	for rows.Next() {
		var i RawTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BankAccountID,
			&i.FioTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.CounterAccountNumber,
			&i.CounterAccountName,
			&i.CounterBankCode,
			&i.CounterBankName,
			&i.Bic,
			&i.VariableSymbol,
			&i.SpecificSymbol,
			&i.ConstantSymbol,
			&i.UserIdentification,
			&i.MessageForRecipient,
			&i.TransactionType,
			&i.Executor,
			&i.Specification,
			&i.Comment,
			&i.InstructionID,
			&i.RawPayload,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaivers = `-- name: ListWaivers :many
SELECT member_number, covers_year, covers_month, reason, created_at
FROM payment_waivers
ORDER BY created_at DESC
`

type ListWaiversRow struct {
	MemberNumber int32     `json:"member_number"`
	CoversYear   int32     `json:"covers_year"`
	CoversMonth  int16     `json:"covers_month"`
	Reason       string    `json:"reason"`
	CreatedAt    time.Time `json:"created_at"`
}

// Every payment_waivers row across all members — backs the dedicated
// Waivers admin tab (list + delete + create), gated the same as manual
// transaction assignment (manage-transactions). Newest first, same convention
// as ListWaiversForMember.
func (q *Queries) ListWaivers(ctx context.Context) ([]ListWaiversRow, error) {
	rows, err := q.db.Query(ctx, listWaivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaiversRow
	for rows.Next() {
		var i ListWaiversRow
		if err := rows.Scan(
			&i.MemberNumber,
			&i.CoversYear,
			&i.CoversMonth,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaiversForMember = `-- name: ListWaiversForMember :many
SELECT covers_year, covers_month, reason, created_at
FROM payment_waivers
WHERE member_number = $1
ORDER BY covers_year DESC, covers_month DESC
`

type ListWaiversForMemberRow struct {
	CoversYear  int32     `json:"covers_year"`
	CoversMonth int16     `json:"covers_month"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
}

// Backs the "why did this month stop showing up as missing" question on the
// payment history panel.
func (q *Queries) ListWaiversForMember(ctx context.Context, memberNumber int32) ([]ListWaiversForMemberRow, error) {
	rows, err := q.db.Query(ctx, listWaiversForMember, memberNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWaiversForMemberRow
	for rows.Next() {
		var i ListWaiversForMemberRow
		if err := rows.Scan(
			&i.CoversYear,
			&i.CoversMonth,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExists = `-- name: MemberExists :one
SELECT EXISTS (SELECT 1 FROM members WHERE member_number = $1) AS exists
`

func (q *Queries) MemberExists(ctx context.Context, memberNumber int32) (bool, error) {
	row := q.db.QueryRow(ctx, memberExists, memberNumber)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const paymentCoverageExists = `-- name: PaymentCoverageExists :one
SELECT EXISTS (
    SELECT 1 FROM payment_coverage
    WHERE member_number = $1
      AND covers_year = $2
      AND covers_month = $3
) AS exists
`

type PaymentCoverageExistsParams struct {
	MemberNumber int32 `json:"member_number"`
	CoversYear   int32 `json:"covers_year"`
	CoversMonth  int16 `json:"covers_month"`
}

// Guards CreatePaymentWaiver: a month with a real payment_coverage row
// doesn't need (and shouldn't get) a waiver.
func (q *Queries) PaymentCoverageExists(ctx context.Context, arg PaymentCoverageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, paymentCoverageExists, arg.MemberNumber, arg.CoversYear, arg.CoversMonth)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const rematchTransactionToMember = `-- name: RematchTransactionToMember :exec
UPDATE processed_transactions
SET member_number = $1,
    category = 'membership_fee',
    matched_by = 'variable_symbol'
WHERE id = $2
`

type RematchTransactionToMemberParams struct {
	MemberNumber *int32 `json:"member_number"`
	ID           int64  `json:"id"`
}

// Only touches member_number/category/matched_by — deliberately leaves
// admin_comment untouched (unlike AssignTransactionToMember, which always
// full-overwrites it), since this is an automatic re-match, not an admin
// action with a comment of its own to record.
func (q *Queries) RematchTransactionToMember(ctx context.Context, arg RematchTransactionToMemberParams) error {
	_, err := q.db.Exec(ctx, rematchTransactionToMember, arg.MemberNumber, arg.ID)
	return err
}

const syncDefaultPaymentIdentifierValidTo = `-- name: SyncDefaultPaymentIdentifierValidTo :exec
UPDATE member_payment_identifiers
SET valid_to = $1
WHERE member_number = $2
  AND variable_symbol = $3
  AND valid_to IS DISTINCT FROM $1
`

type SyncDefaultPaymentIdentifierValidToParams struct {
	ValidTo        pgtype.Date `json:"valid_to"`
	MemberNumber   int32       `json:"member_number"`
	VariableSymbol string      `json:"variable_symbol"`
}

// Mirrors members.fee_stop_date onto the default payment identifier's valid_to
// (variable_symbol == member_number): fee liability ended -> row closed with that
// date, fee_stop_date cleared in Orca -> row reopened (valid_to = NULL). The sync
// owns this row's window authoritatively (valid_from = fee_start_date, valid_to =
// fee_stop_date). To point a member at a different variable symbol, add a *new*
// member_payment_identifiers row (different variable_symbol, its own valid_from) —
// that row has variable_symbol != member_number so this UPDATE never touches it.
// The IS DISTINCT FROM guard makes a steady-state run write nothing.
func (q *Queries) SyncDefaultPaymentIdentifierValidTo(ctx context.Context, arg SyncDefaultPaymentIdentifierValidToParams) error {
	_, err := q.db.Exec(ctx, syncDefaultPaymentIdentifierValidTo, arg.ValidTo, arg.MemberNumber, arg.VariableSymbol)
	return err
}

const unassignTransaction = `-- name: UnassignTransaction :one
UPDATE processed_transactions
SET member_number = NULL,
    matched_by = NULL,
    category = $1
WHERE id = $2
RETURNING id
`

type UnassignTransactionParams struct {
	Category string `json:"category"`
	ID       int64  `json:"id"`
}

// Reverts a manual (or automatic) match: clears the member and matched_by, and
// resets category to the direction-based default the caller passes in.
func (q *Queries) UnassignTransaction(ctx context.Context, arg UnassignTransactionParams) (int64, error) {
	row := q.db.QueryRow(ctx, unassignTransaction, arg.Category, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE bank_accounts
SET display_name = $1,
    fio_token_encrypted = CASE
        WHEN $2::text IS NOT NULL
        THEN pgp_sym_encrypt($2::text, $3::text)
        ELSE fio_token_encrypted
    END
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, fio_account_id, iban, currency, display_name, created_at,
          (fio_token_encrypted IS NOT NULL)::boolean AS has_token
`

type UpdateBankAccountParams struct {
	DisplayName   string  `json:"display_name"`
	FioToken      *string `json:"fio_token"`
	EncryptionKey string  `json:"encryption_key"`
	ID            int32   `json:"id"`
}

type UpdateBankAccountRow struct {
	ID           int32     `json:"id"`
	FioAccountID string    `json:"fio_account_id"`
	Iban         *string   `json:"iban"`
	Currency     string    `json:"currency"`
	DisplayName  string    `json:"display_name"`
	CreatedAt    time.Time `json:"created_at"`
	HasToken     bool      `json:"has_token"`
}

// fio_account_id/iban/currency are properties of the real Fio account, not
// editable metadata — only our own display_name and the sync token can change
// here. fio_token is sqlc.narg: NULL means "leave the existing token
// untouched", any non-NULL value re-encrypts and replaces it (see
// CreateBankAccount for the same pgp_sym_encrypt pattern).
// Only touches active accounts (deleted_at IS NULL) — a soft-deleted account
// is a historical record, not something to edit; 0 rows affected reads as
// "not found" either way (missing id or soft-deleted id).
func (q *Queries) UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (UpdateBankAccountRow, error) {
	row := q.db.QueryRow(ctx, updateBankAccount,
		arg.DisplayName,
		arg.FioToken,
		arg.EncryptionKey,
		arg.ID,
	)
	var i UpdateBankAccountRow
	err := row.Scan(
		&i.ID,
		&i.FioAccountID,
		&i.Iban,
		&i.Currency,
		&i.DisplayName,
		&i.CreatedAt,
		&i.HasToken,
	)
	return i, err
}

const updateBankAccountBalance = `-- name: UpdateBankAccountBalance :exec
UPDATE bank_accounts SET balance = $1, balance_as_of = now()
WHERE id = $2
`

type UpdateBankAccountBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	ID      int32          `json:"id"`
}

// Internal use only, written by the cursor-based sync path only (syncjob's
// syncAccount) — never by backfill, whose date range is often in the past,
// so its own closingBalance wouldn't be "current". Both columns null until
// the account's first successful sync. balance_as_of is set by Postgres
// (now()), not passed in from Go — same convention as sync_fio_runs.started_at
// etc., avoids any app/DB clock skew.
func (q *Queries) UpdateBankAccountBalance(ctx context.Context, arg UpdateBankAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBankAccountBalance, arg.Balance, arg.ID)
	return err
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO members (member_number, fee_start_date, fee_stop_date, active, sub, workplace_executive_committee_sub)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (member_number) DO UPDATE
SET fee_start_date = EXCLUDED.fee_start_date,
    fee_stop_date = EXCLUDED.fee_stop_date,
    active = EXCLUDED.active,
    sub = EXCLUDED.sub,
    workplace_executive_committee_sub = EXCLUDED.workplace_executive_committee_sub
`

type UpsertMemberParams struct {
	MemberNumber                   int32       `json:"member_number"`
	FeeStartDate                   pgtype.Date `json:"fee_start_date"`
	FeeStopDate                    pgtype.Date `json:"fee_stop_date"`
	Active                         bool        `json:"active"`
	Sub                            pgtype.UUID `json:"sub"`
	WorkplaceExecutiveCommitteeSub pgtype.UUID `json:"workplace_executive_committee_sub"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.MemberNumber,
		arg.FeeStartDate,
		arg.FeeStopDate,
		arg.Active,
		arg.Sub,
		arg.WorkplaceExecutiveCommitteeSub,
	)
	return err
}
