// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Manual categorization, with or without a member match (see
	// docs/logic-design.md "Manual Assignment & Coverage") — member_number and
	// matched_by are both nullable so a category-only edit (no member) just
	// passes both as NULL. Coverage rows are managed separately by the caller in
	// the same DB transaction.
	AssignTransactionToMember(ctx context.Context, arg AssignTransactionToMemberParams) (int64, error)
	CategoryExists(ctx context.Context, name string) (bool, error)
	// fio_token is encrypted at rest via pgcrypto (pgp_sym_encrypt) using
	// encryption_key (BANK_TOKEN_ENCRYPTION_KEY env var) — never stored in the DB
	// itself. RETURNING list explicitly excludes fio_token_encrypted so the
	// ciphertext (and a fortiori the token) is never echoed back to the caller.
	CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (CreateBankAccountRow, error)
	// is_mandatory is never set true here — only the four seeded in
	// migrations/20260910000001_add_transaction_categories.sql are mandatory.
	CreateCategory(ctx context.Context, name string) (TransactionCategory, error)
	// ON CONFLICT DO NOTHING + :execrows (same pattern as InsertCoverageRow) so
	// the caller can tell when a second payment lands on an already-covered
	// month — see internal/processing/processing.go's log line, since this path
	// (unlike the manual assignment endpoint) has no HTTP response to surface it
	// through.
	CreatePaymentCoverage(ctx context.Context, arg CreatePaymentCoverageParams) (int64, error)
	// ON CONFLICT DO NOTHING + :execrows, same idempotent-insert pattern as
	// CreatePaymentCoverage/InsertCoverageRow — calling this twice for the same
	// month is a no-op (0 rows affected), not an error, since the caller's
	// intent ("this month is written off") is already satisfied.
	CreatePaymentWaiver(ctx context.Context, arg CreatePaymentWaiverParams) (int64, error)
	CreateProcessedTransaction(ctx context.Context, arg CreateProcessedTransactionParams) (ProcessedTransaction, error)
	CreateSyncFioRun(ctx context.Context, bankAccountID int32) (SyncFioRun, error)
	CreateSyncOrcaRun(ctx context.Context) (SyncOrcaRun, error)
	// Soft delete: raw_transactions/sync_fio_runs reference bank_accounts.id with
	// no ON DELETE clause (see initial_schema.sql), so a hard delete would fail
	// once an account has synced history — and the row also needs to stick around
	// for admins to see it used to exist (see ListBankAccounts). deleted_at IS
	// NULL in the WHERE guards against re-timestamping an already-deleted row;
	// :execrows lets handler.DeleteBankAccount tell "already gone" (0 rows) from
	// "deleted just now" (1 row) and return 404 vs 204 accordingly.
	DeleteBankAccount(ctx context.Context, id int32) (int64, error)
	// The is_mandatory=false guard means a mandatory category and a missing one
	// both come back as 0 rows affected — the caller (handler.DeleteCategory)
	// checks GetCategory first to tell those two cases apart. A category still
	// referenced by processed_transactions.category fails this with a foreign
	// key violation instead (see processed_transactions_category_fkey).
	DeleteCategory(ctx context.Context, name string) (int64, error)
	DeleteCoverageForTransaction(ctx context.Context, processedTransactionID int64) error
	// Undoes a waiver (the admin changed their mind, or waived the wrong
	// month) — the month reappears in missing-payment lists on the next read,
	// same as any other computed-on-read state here.
	DeletePaymentWaiver(ctx context.Context, arg DeletePaymentWaiverParams) (int64, error)
	// Seeds the auto-generated "default" payment identifier for a member: variable
	// symbol == member_number, valid from their fee_start_date. Runs on every Orca
	// sync. DO NOTHING on conflict so a re-run is a no-op. Skipped by the caller when
	// fee_start_date is null (member not yet liable, and valid_from is NOT NULL).
	EnsureDefaultPaymentIdentifier(ctx context.Context, arg EnsureDefaultPaymentIdentifierParams) error
	// Run once at server startup, before the scheduler starts: any row still
	// 'running' predates this process (a single instance drives all syncs, so a
	// 'running' row at boot means the prior process died — crash, panic, kill —
	// between CreateSyncFioRun and FinishSyncFioRun and never got to close it).
	FailStaleSyncFioRuns(ctx context.Context) (int64, error)
	// See FailStaleSyncFioRuns — same reasoning, run at startup.
	FailStaleSyncOrcaRuns(ctx context.Context) (int64, error)
	FindMemberByVariableSymbol(ctx context.Context, arg FindMemberByVariableSymbolParams) (int32, error)
	FinishSyncFioRun(ctx context.Context, arg FinishSyncFioRunParams) error
	FinishSyncOrcaRun(ctx context.Context, arg FinishSyncOrcaRunParams) error
	// Internal use only (the manual "sync now" trigger — see
	// syncjob.SyncOneAccount) — single-row counterpart of
	// ListBankAccountsWithToken, same never-expose-over-HTTP caveat.
	GetBankAccountWithToken(ctx context.Context, arg GetBankAccountWithTokenParams) (GetBankAccountWithTokenRow, error)
	GetCategory(ctx context.Context, name string) (TransactionCategory, error)
	GetMaxFioTransactionID(ctx context.Context, bankAccountID int32) (int64, error)
	GetMemberNumberBySub(ctx context.Context, sub pgtype.UUID) (int32, error)
	// Backs the workplace-rep access path on GET /payments/{member_number}/history
	// (see docs/logic-design.md "Payment History Endpoint"): a caller without the
	// admin payment-history role can still see this member if the returned value
	// is non-null and matches one of the caller's own Keycloak groups.
	GetMemberWorkplaceSub(ctx context.Context, memberNumber int32) (pgtype.UUID, error)
	GetPaymentHistory(ctx context.Context, memberNumber int32) ([]GetPaymentHistoryRow, error)
	GetPaymentWaiver(ctx context.Context, arg GetPaymentWaiverParams) (GetPaymentWaiverRow, error)
	// Budgeting view (see docs/logic-design.md "Transaction Category Summary"):
	// totals grouped by direction/category/currency only — no member_number, no
	// counterparty, no per-transaction rows, so this is safe for the
	// widely-held view-budget role (unlike ListTransactions). SUM(ABS(amount))
	// so an "outgoing" total reads as a positive spend figure rather than the
	// signed value raw_transactions stores it as.
	GetTransactionCategorySummary(ctx context.Context, arg GetTransactionCategorySummaryParams) ([]GetTransactionCategorySummaryRow, error)
	// One row for the transaction browser's detail / edit view — same columns as
	// ListTransactions minus the window count. Covered months come from
	// ListCoverageForTransaction.
	GetTransactionDetail(ctx context.Context, id int64) (GetTransactionDetailRow, error)
	// ON CONFLICT DO NOTHING + :execrows so the caller can tell which requested
	// month was already covered by a *different* transaction (0 rows affected) and
	// report it, rather than silently dropping it.
	InsertCoverageRow(ctx context.Context, arg InsertCoverageRowParams) (int64, error)
	InsertRawTransaction(ctx context.Context, arg InsertRawTransactionParams) (int64, error)
	// Admin-facing list (GET /account) — deliberately excludes the Fio token.
	// Includes soft-deleted accounts (is_active = false) so admins still see them
	// in the UI, crossed out, as a record that the account used to exist. For the
	// token itself, see ListBankAccountsWithToken (internal use only).
	ListBankAccounts(ctx context.Context) ([]ListBankAccountsRow, error)
	// Internal use only (the Fio sync job) — includes the decrypted Fio token.
	// Includes soft-deleted accounts (is_active = false); the sync job itself is
	// responsible for skipping those rather than filtering here, since "should
	// this account sync" is business logic, not a storage-layer concern. Never
	// expose this query's result over HTTP. encryption_key is bound as a query
	// parameter via pgp_sym_decrypt, never interpolated into SQL text. fio_token
	// is NULL for any account not yet backfilled with a token.
	ListBankAccountsWithToken(ctx context.Context, encryptionKey string) ([]ListBankAccountsWithTokenRow, error)
	ListCategories(ctx context.Context) ([]TransactionCategory, error)
	ListCoverageForTransaction(ctx context.Context, processedTransactionID int64) ([]ListCoverageForTransactionRow, error)
	// Admin event log (GET /event-logs): sync_fio_runs and sync_orca_runs merged
	// into one feed, newest first. No filters — just a simple paged log, same
	// limit/offset + count(*) OVER () pagination pattern as ListTransactions.
	// detail is the bank account's display name for a fio_sync row, NULL for
	// orca_sync (there's no per-account breakdown for the member sync).
	ListEventLogs(ctx context.Context, arg ListEventLogsParams) ([]ListEventLogsRow, error)
	// Members who were liable for the membership fee in the given year/month but
	// have no payment_coverage row for it. "Liable" = fee_start_date is set (the
	// member_arrears view enforces this) and the target month falls within
	// [fee_start_date, upper bound] at month granularity, where upper bound is
	// COALESCE(fee_stop_date, CURRENT_DATE) capped at CURRENT_DATE - 2 months: dues
	// for month M are due by the end of month M+1 (a recurring one-month grace,
	// not just onboarding — see docs/logic-design.md "Missed Payment Detection"),
	// so M only counts as liable-and-overdue once M+1 has also fully elapsed.
	//
	// total_missed_months comes from the member_arrears view: a total-arrears figure
	// independent of the queried month (every unpaid month across the member's full
	// liability window). Always >= 1 here, since the queried month is one of them.
	// has_ever_paid (also from member_arrears) is false for a member with zero
	// payment_coverage rows ever — distinguishes "never started paying" from
	// "usually pays, missed a month" for follow-up prioritization.
	// Rows are ordered by it descending ("top offenders first"), member_number
	// breaking ties. See docs/logic-design.md "Missed Payment Detection".
	ListMembersMissingPayment(ctx context.Context, arg ListMembersMissingPaymentParams) ([]MemberArrear, error)
	// Workplace-rep counterpart to ListMembersMissingPayment — same shape and
	// logic, scoped to members in any of the caller's workplace groups instead of
	// every member. See that query's comment for the liability-window logic.
	ListMembersMissingPaymentForWorkplace(ctx context.Context, arg ListMembersMissingPaymentForWorkplaceParams) ([]MemberArrear, error)
	// Members who missed at least one liable month during the given calendar year —
	// the whole-year counterpart of ListMembersMissingPayment. Same
	// {member_number, total_missed_months, has_ever_paid} shape and ordering;
	// total_missed_months/has_ever_paid are still the full-liability-window
	// figures (member_arrears view), not scoped to the year. See
	// docs/logic-design.md "Missed Payment Detection".
	ListMembersMissingPaymentInYear(ctx context.Context, year int32) ([]MemberArrear, error)
	// Workplace-rep counterpart to ListMembersMissingPaymentInYear — same shape
	// and logic, scoped to members in any of the caller's workplace groups.
	ListMembersMissingPaymentInYearForWorkplace(ctx context.Context, arg ListMembersMissingPaymentInYearForWorkplaceParams) ([]MemberArrear, error)
	// Admin transaction browser: processed_transactions enriched with their
	// raw_transactions row, with optional filters. Every filter arg is nullable —
	// NULL / omitted means "don't filter on this". total_count is the full match
	// count ignoring LIMIT/OFFSET (window aggregate) so the caller can paginate. See
	// docs/logic-design.md "Transaction Browser".
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	ListUnprocessedTransactions(ctx context.Context) ([]RawTransaction, error)
	// Every payment_waivers row across all members — backs the dedicated
	// Waivers admin tab (list + delete + create), gated the same as manual
	// transaction assignment (manage-transactions). See docs/logic-design.md
	// "Payment Waivers". Newest first, same convention as ListWaiversForMember.
	ListWaivers(ctx context.Context) ([]ListWaiversRow, error)
	// Backs the "why did this month stop showing up as missing" question on the
	// payment history panel — see docs/logic-design.md "Payment Waivers".
	ListWaiversForMember(ctx context.Context, memberNumber int32) ([]ListWaiversForMemberRow, error)
	MemberExists(ctx context.Context, memberNumber int32) (bool, error)
	// Guards CreatePaymentWaiver: a month with a real payment_coverage row
	// doesn't need (and shouldn't get) a waiver — see docs/logic-design.md
	// "Payment Waivers".
	PaymentCoverageExists(ctx context.Context, arg PaymentCoverageExistsParams) (bool, error)
	// Mirrors members.fee_stop_date onto the default payment identifier's valid_to
	// (variable_symbol == member_number): fee liability ended -> row closed with that
	// date, fee_stop_date cleared in Orca -> row reopened (valid_to = NULL). The sync
	// owns this row's window authoritatively (valid_from = fee_start_date, valid_to =
	// fee_stop_date). To point a member at a different variable symbol, add a *new*
	// member_payment_identifiers row (different variable_symbol, its own valid_from) —
	// that row has variable_symbol != member_number so this UPDATE never touches it.
	// The IS DISTINCT FROM guard makes a steady-state run write nothing.
	SyncDefaultPaymentIdentifierValidTo(ctx context.Context, arg SyncDefaultPaymentIdentifierValidToParams) error
	// Reverts a manual (or automatic) match: clears the member and matched_by, and
	// resets category to the direction-based default the caller passes in.
	UnassignTransaction(ctx context.Context, arg UnassignTransactionParams) (int64, error)
	// fio_account_id/iban/currency are properties of the real Fio account, not
	// editable metadata — only our own display_name and the sync token can change
	// here. fio_token is sqlc.narg: NULL means "leave the existing token
	// untouched", any non-NULL value re-encrypts and replaces it (see
	// CreateBankAccount for the same pgp_sym_encrypt pattern).
	// Only touches active accounts (deleted_at IS NULL) — a soft-deleted account
	// is a historical record, not something to edit; 0 rows affected reads as
	// "not found" either way (missing id or soft-deleted id).
	UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (UpdateBankAccountRow, error)
	UpsertMember(ctx context.Context, arg UpsertMemberParams) error
}

var _ Querier = (*Queries)(nil)
