// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts (fio_account_id, iban, currency, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, fio_account_id, iban, currency, display_name, created_at
`

type CreateBankAccountParams struct {
	FioAccountID string  `json:"fio_account_id"`
	Iban         *string `json:"iban"`
	Currency     string  `json:"currency"`
	DisplayName  string  `json:"display_name"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.FioAccountID,
		arg.Iban,
		arg.Currency,
		arg.DisplayName,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.FioAccountID,
		&i.Iban,
		&i.Currency,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentCoverage = `-- name: CreatePaymentCoverage :exec
INSERT INTO payment_coverage (processed_transaction_id, member_number, covers_year, covers_month)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_number, covers_year, covers_month) DO NOTHING
`

type CreatePaymentCoverageParams struct {
	ProcessedTransactionID int64 `json:"processed_transaction_id"`
	MemberNumber           int32 `json:"member_number"`
	CoversYear             int32 `json:"covers_year"`
	CoversMonth            int16 `json:"covers_month"`
}

func (q *Queries) CreatePaymentCoverage(ctx context.Context, arg CreatePaymentCoverageParams) error {
	_, err := q.db.Exec(ctx, createPaymentCoverage,
		arg.ProcessedTransactionID,
		arg.MemberNumber,
		arg.CoversYear,
		arg.CoversMonth,
	)
	return err
}

const createProcessedTransaction = `-- name: CreateProcessedTransaction :one
INSERT INTO processed_transactions (raw_transaction_id, member_number, category, direction, matched_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, raw_transaction_id, member_number, category, direction, matched_by, is_public_visible, processed_at
`

type CreateProcessedTransactionParams struct {
	RawTransactionID int64   `json:"raw_transaction_id"`
	MemberNumber     *int32  `json:"member_number"`
	Category         string  `json:"category"`
	Direction        string  `json:"direction"`
	MatchedBy        *string `json:"matched_by"`
}

func (q *Queries) CreateProcessedTransaction(ctx context.Context, arg CreateProcessedTransactionParams) (ProcessedTransaction, error) {
	row := q.db.QueryRow(ctx, createProcessedTransaction,
		arg.RawTransactionID,
		arg.MemberNumber,
		arg.Category,
		arg.Direction,
		arg.MatchedBy,
	)
	var i ProcessedTransaction
	err := row.Scan(
		&i.ID,
		&i.RawTransactionID,
		&i.MemberNumber,
		&i.Category,
		&i.Direction,
		&i.MatchedBy,
		&i.IsPublicVisible,
		&i.ProcessedAt,
	)
	return i, err
}

const createSyncFioRun = `-- name: CreateSyncFioRun :one
INSERT INTO sync_fio_runs (bank_account_id, status)
VALUES ($1, 'running')
RETURNING id, bank_account_id, started_at, finished_at, status, transactions_fetched, transactions_inserted, error_message
`

func (q *Queries) CreateSyncFioRun(ctx context.Context, bankAccountID int32) (SyncFioRun, error) {
	row := q.db.QueryRow(ctx, createSyncFioRun, bankAccountID)
	var i SyncFioRun
	err := row.Scan(
		&i.ID,
		&i.BankAccountID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.TransactionsFetched,
		&i.TransactionsInserted,
		&i.ErrorMessage,
	)
	return i, err
}

const createSyncOrcaRun = `-- name: CreateSyncOrcaRun :one
INSERT INTO sync_orca_runs (status)
VALUES ('running')
RETURNING id, started_at, finished_at, status, members_fetched, members_upserted, error_message
`

func (q *Queries) CreateSyncOrcaRun(ctx context.Context) (SyncOrcaRun, error) {
	row := q.db.QueryRow(ctx, createSyncOrcaRun)
	var i SyncOrcaRun
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.MembersFetched,
		&i.MembersUpserted,
		&i.ErrorMessage,
	)
	return i, err
}

const ensureDefaultPaymentIdentifier = `-- name: EnsureDefaultPaymentIdentifier :exec
INSERT INTO member_payment_identifiers (member_number, variable_symbol, valid_from)
VALUES ($1, $2, $3)
ON CONFLICT (variable_symbol, valid_from) DO NOTHING
`

type EnsureDefaultPaymentIdentifierParams struct {
	MemberNumber   int32     `json:"member_number"`
	VariableSymbol string    `json:"variable_symbol"`
	ValidFrom      time.Time `json:"valid_from"`
}

// Seeds the auto-generated "default" payment identifier for a member: variable
// symbol == member_number, valid from their fee_start_date. Runs on every Orca
// sync. DO NOTHING on conflict so a re-run is a no-op. Skipped by the caller when
// fee_start_date is null (member not yet liable, and valid_from is NOT NULL).
func (q *Queries) EnsureDefaultPaymentIdentifier(ctx context.Context, arg EnsureDefaultPaymentIdentifierParams) error {
	_, err := q.db.Exec(ctx, ensureDefaultPaymentIdentifier, arg.MemberNumber, arg.VariableSymbol, arg.ValidFrom)
	return err
}

const findMemberByVariableSymbol = `-- name: FindMemberByVariableSymbol :one
SELECT member_number FROM member_payment_identifiers
WHERE variable_symbol = $1
    AND valid_from <= $2
    AND (valid_to IS NULL OR valid_to >= $2)
ORDER BY valid_from DESC
LIMIT 1
`

type FindMemberByVariableSymbolParams struct {
	VariableSymbol  string    `json:"variable_symbol"`
	TransactionDate time.Time `json:"transaction_date"`
}

func (q *Queries) FindMemberByVariableSymbol(ctx context.Context, arg FindMemberByVariableSymbolParams) (int32, error) {
	row := q.db.QueryRow(ctx, findMemberByVariableSymbol, arg.VariableSymbol, arg.TransactionDate)
	var member_number int32
	err := row.Scan(&member_number)
	return member_number, err
}

const finishSyncFioRun = `-- name: FinishSyncFioRun :exec
UPDATE sync_fio_runs
SET finished_at = now(),
    status = $1,
    transactions_fetched = $2,
    transactions_inserted = $3,
    error_message = $4
WHERE id = $5
`

type FinishSyncFioRunParams struct {
	Status               string  `json:"status"`
	TransactionsFetched  *int32  `json:"transactions_fetched"`
	TransactionsInserted *int32  `json:"transactions_inserted"`
	ErrorMessage         *string `json:"error_message"`
	ID                   int64   `json:"id"`
}

func (q *Queries) FinishSyncFioRun(ctx context.Context, arg FinishSyncFioRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncFioRun,
		arg.Status,
		arg.TransactionsFetched,
		arg.TransactionsInserted,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const finishSyncOrcaRun = `-- name: FinishSyncOrcaRun :exec
UPDATE sync_orca_runs
SET finished_at = now(),
    status = $1,
    members_fetched = $2,
    members_upserted = $3,
    error_message = $4
WHERE id = $5
`

type FinishSyncOrcaRunParams struct {
	Status          string  `json:"status"`
	MembersFetched  *int32  `json:"members_fetched"`
	MembersUpserted *int32  `json:"members_upserted"`
	ErrorMessage    *string `json:"error_message"`
	ID              int64   `json:"id"`
}

func (q *Queries) FinishSyncOrcaRun(ctx context.Context, arg FinishSyncOrcaRunParams) error {
	_, err := q.db.Exec(ctx, finishSyncOrcaRun,
		arg.Status,
		arg.MembersFetched,
		arg.MembersUpserted,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const getMaxFioTransactionID = `-- name: GetMaxFioTransactionID :one
SELECT COALESCE(MAX(fio_transaction_id), 0)::bigint AS max_id
FROM raw_transactions
WHERE bank_account_id = $1
`

func (q *Queries) GetMaxFioTransactionID(ctx context.Context, bankAccountID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxFioTransactionID, bankAccountID)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const getMemberNumberBySub = `-- name: GetMemberNumberBySub :one
SELECT member_number FROM members WHERE sub = $1
`

func (q *Queries) GetMemberNumberBySub(ctx context.Context, sub pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMemberNumberBySub, sub)
	var member_number int32
	err := row.Scan(&member_number)
	return member_number, err
}

const getPaymentHistory = `-- name: GetPaymentHistory :many
SELECT pc.covers_year, pc.covers_month,
       rt.transaction_date, rt.amount, rt.currency,
       pc.processed_transaction_id
FROM payment_coverage pc
JOIN processed_transactions pt ON pt.id = pc.processed_transaction_id
JOIN raw_transactions rt ON rt.id = pt.raw_transaction_id
WHERE pc.member_number = $1
ORDER BY pc.covers_year DESC, pc.covers_month DESC
`

type GetPaymentHistoryRow struct {
	CoversYear             int32     `json:"covers_year"`
	CoversMonth            int16     `json:"covers_month"`
	TransactionDate        time.Time `json:"transaction_date"`
	Amount                 string    `json:"amount"`
	Currency               string    `json:"currency"`
	ProcessedTransactionID int64     `json:"processed_transaction_id"`
}

func (q *Queries) GetPaymentHistory(ctx context.Context, memberNumber int32) ([]GetPaymentHistoryRow, error) {
	rows, err := q.db.Query(ctx, getPaymentHistory, memberNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentHistoryRow
	for rows.Next() {
		var i GetPaymentHistoryRow
		if err := rows.Scan(
			&i.CoversYear,
			&i.CoversMonth,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.ProcessedTransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRawTransaction = `-- name: InsertRawTransaction :execrows
INSERT INTO raw_transactions (
    bank_account_id, fio_transaction_id, transaction_date, amount, currency,
    counter_account_number, counter_account_name, counter_bank_code, counter_bank_name, bic,
    variable_symbol, specific_symbol, constant_symbol,
    user_identification, message_for_recipient, transaction_type, executor, specification, comment, instruction_id,
    raw_payload
) VALUES (
    $1,
    $2,
    $3,
    $4::numeric,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
ON CONFLICT (bank_account_id, fio_transaction_id) DO NOTHING
`

type InsertRawTransactionParams struct {
	BankAccountID        int32     `json:"bank_account_id"`
	FioTransactionID     int64     `json:"fio_transaction_id"`
	TransactionDate      time.Time `json:"transaction_date"`
	Amount               string    `json:"amount"`
	Currency             string    `json:"currency"`
	CounterAccountNumber *string   `json:"counter_account_number"`
	CounterAccountName   *string   `json:"counter_account_name"`
	CounterBankCode      *string   `json:"counter_bank_code"`
	CounterBankName      *string   `json:"counter_bank_name"`
	Bic                  *string   `json:"bic"`
	VariableSymbol       *string   `json:"variable_symbol"`
	SpecificSymbol       *string   `json:"specific_symbol"`
	ConstantSymbol       *string   `json:"constant_symbol"`
	UserIdentification   *string   `json:"user_identification"`
	MessageForRecipient  *string   `json:"message_for_recipient"`
	TransactionType      *string   `json:"transaction_type"`
	Executor             *string   `json:"executor"`
	Specification        *string   `json:"specification"`
	Comment              *string   `json:"comment"`
	InstructionID        *string   `json:"instruction_id"`
	RawPayload           []byte    `json:"raw_payload"`
}

func (q *Queries) InsertRawTransaction(ctx context.Context, arg InsertRawTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRawTransaction,
		arg.BankAccountID,
		arg.FioTransactionID,
		arg.TransactionDate,
		arg.Amount,
		arg.Currency,
		arg.CounterAccountNumber,
		arg.CounterAccountName,
		arg.CounterBankCode,
		arg.CounterBankName,
		arg.Bic,
		arg.VariableSymbol,
		arg.SpecificSymbol,
		arg.ConstantSymbol,
		arg.UserIdentification,
		arg.MessageForRecipient,
		arg.TransactionType,
		arg.Executor,
		arg.Specification,
		arg.Comment,
		arg.InstructionID,
		arg.RawPayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, fio_account_id, iban, currency, display_name, created_at FROM bank_accounts ORDER BY id
`

func (q *Queries) ListBankAccounts(ctx context.Context) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.FioAccountID,
			&i.Iban,
			&i.Currency,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT member_number, fee_start_date, active, created_at, sub, fee_stop_date FROM members ORDER BY member_number
`

func (q *Queries) ListMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MemberNumber,
			&i.FeeStartDate,
			&i.Active,
			&i.CreatedAt,
			&i.Sub,
			&i.FeeStopDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedTransactions = `-- name: ListUnprocessedTransactions :many
SELECT rt.id, rt.bank_account_id, rt.fio_transaction_id, rt.transaction_date, rt.amount, rt.currency, rt.counter_account_number, rt.counter_account_name, rt.counter_bank_code, rt.counter_bank_name, rt.bic, rt.variable_symbol, rt.specific_symbol, rt.constant_symbol, rt.user_identification, rt.message_for_recipient, rt.transaction_type, rt.executor, rt.specification, rt.comment, rt.instruction_id, rt.raw_payload, rt.synced_at FROM raw_transactions rt
LEFT JOIN processed_transactions pt ON pt.raw_transaction_id = rt.id
WHERE pt.id IS NULL
ORDER BY rt.id
`

func (q *Queries) ListUnprocessedTransactions(ctx context.Context) ([]RawTransaction, error) {
	rows, err := q.db.Query(ctx, listUnprocessedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawTransaction
	for rows.Next() {
		var i RawTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BankAccountID,
			&i.FioTransactionID,
			&i.TransactionDate,
			&i.Amount,
			&i.Currency,
			&i.CounterAccountNumber,
			&i.CounterAccountName,
			&i.CounterBankCode,
			&i.CounterBankName,
			&i.Bic,
			&i.VariableSymbol,
			&i.SpecificSymbol,
			&i.ConstantSymbol,
			&i.UserIdentification,
			&i.MessageForRecipient,
			&i.TransactionType,
			&i.Executor,
			&i.Specification,
			&i.Comment,
			&i.InstructionID,
			&i.RawPayload,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncDefaultPaymentIdentifierValidTo = `-- name: SyncDefaultPaymentIdentifierValidTo :exec
UPDATE member_payment_identifiers
SET valid_to = $1
WHERE member_number = $2
  AND variable_symbol = $3
  AND valid_to IS DISTINCT FROM $1
`

type SyncDefaultPaymentIdentifierValidToParams struct {
	ValidTo        pgtype.Date `json:"valid_to"`
	MemberNumber   int32       `json:"member_number"`
	VariableSymbol string      `json:"variable_symbol"`
}

// Mirrors members.fee_stop_date onto the default payment identifier's valid_to
// (variable_symbol == member_number): fee liability ended -> row closed with that
// date, fee_stop_date cleared in Orca -> row reopened (valid_to = NULL). The sync
// owns this row's window authoritatively (valid_from = fee_start_date, valid_to =
// fee_stop_date). To point a member at a different variable symbol, add a *new*
// member_payment_identifiers row (different variable_symbol, its own valid_from) —
// that row has variable_symbol != member_number so this UPDATE never touches it.
// The IS DISTINCT FROM guard makes a steady-state run write nothing.
func (q *Queries) SyncDefaultPaymentIdentifierValidTo(ctx context.Context, arg SyncDefaultPaymentIdentifierValidToParams) error {
	_, err := q.db.Exec(ctx, syncDefaultPaymentIdentifierValidTo, arg.ValidTo, arg.MemberNumber, arg.VariableSymbol)
	return err
}

const upsertMember = `-- name: UpsertMember :exec
INSERT INTO members (member_number, fee_start_date, fee_stop_date, active, sub)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (member_number) DO UPDATE
SET fee_start_date = EXCLUDED.fee_start_date,
    fee_stop_date = EXCLUDED.fee_stop_date,
    active = EXCLUDED.active,
    sub = EXCLUDED.sub
`

type UpsertMemberParams struct {
	MemberNumber int32       `json:"member_number"`
	FeeStartDate pgtype.Date `json:"fee_start_date"`
	FeeStopDate  pgtype.Date `json:"fee_stop_date"`
	Active       bool        `json:"active"`
	Sub          pgtype.UUID `json:"sub"`
}

func (q *Queries) UpsertMember(ctx context.Context, arg UpsertMemberParams) error {
	_, err := q.db.Exec(ctx, upsertMember,
		arg.MemberNumber,
		arg.FeeStartDate,
		arg.FeeStopDate,
		arg.Active,
		arg.Sub,
	)
	return err
}
